<section id="headline2">
<div class="container">
<h3>Proposta PróÉtica</small></h3>
</div>
</section>

<section class="container" >
<div class="vertical-space1"></div>
<div class="sixteen columns">
<div class="title">
<h4>Veja abaixo um modelo de nossa proposta de serviços:</h4>
</div> 

<span class="acc-trigger"><a href="#"><strong>1. Histórico:</strong></a></span>
<div class="acc-container">
<div class="content">
<p style="text-align: justify;">O Projeto PróÉtica está fundamentado na gestão da conscientização ética, na mitigação de riscos de fraudes e no combate a corrupção.</p>
<p style="text-align: justify;">O projeto identificará os fluxos de informações das diversas rotinas de cada área e avaliará se os resultados alcançados atendem os requisitos exigidos pela Controladoria Geral da União (CGU) para que as empresas possam integrar seu cadastro Empresa PróÉtica. Os casos de não conformidade serão apontados em plano de ação que indicará soluções imediatas, por meio de ajustes nos processos das áreas afetadas.</p>
<p style="text-align: justify;">Disponibilizamos um canal de comunicação para esclarecimentos de dúvidas e denúncias de desvio de conduta ou sugestões de melhorias. Esse canal de comunicação tem a função de disponibilizar aos funcionários, clientes, fornecedores e colaboradores uma ferramenta segura para se expressar perante os administradores das empresas/entidades. </p>
</div>
</div>

<span class="acc-trigger"><a href="#"><strong>2. Objetivo:</strong></a></span>
<div class="acc-container">
<div class="content">
<p style="text-align: justify;">O Pró-Ética objetiva alinhar a gestão ética da empresa às especificações do cadastro Empresa Pró-Ética da Controladoria Geral da União e otimizar os resultados alcançados pela empresa, reduzindo riscos de fraude e corrupção por meio da gestão ética corporativa. </p>
</div>
</div>

<span class="acc-trigger"><a href="#"><strong>3. Serviços:</strong></a></span>
<div class="acc-container">
<div class="content">


<p style="text-align: justify;">Os serviços realizados pelo PróÉtica são baseados em atividades que abrangem as seguintes fases:</p>

<h4><strong>Gestão Ética</strong></h4>
<ul>
<li class="check">Avaliação dos valores éticos corporativos por meio da identificação dos problemas do dia-a-dia e do comportamento dos executivos, funcionários e colaboradores na solução dos entraves de cada processo e rotinas das diversas atividades dos departamentos das empresas.</li>
<li class="check">Estabelecimento de uma agenda de entrevistas com executivos, gerentes, funcionários, colaboradores e fornecedores de acordo com o grau de risco dos setores mais expostos a desperdícios, fraudes e corrupção.</li>
<li class="check">Elaboração de guia de informações e ações de postura ética. O código de conduta ética é uma coletânea das principais atitudes que devem ser tomadas em determinadas situações envolvendo rotinas de trabalho e atividades compartilhadas com colaboradores, fornecedores e parceiros, clientes, sociedade, comunidade e o governo.</li>
<li class="check">Dar divulgação e treinamento aos funcionários e administradores sobre o Código de Conduta Ética desenvolvido para a empresa ou já existente.</li>
</ul>
<h4><strong>Canal de Comunicação e Denúncias</strong></h4>

<p style="text-align: justify;">O PróÉtica estará vinculado ao Portal PróÉtica que é um canal de comunicações para esclarecimento de dúvidas e denúncias sobre desvio de conduta e sugestões de melhorias. Este canal de comunicações tem a função de disponibilizar aos funcionários, clientes, fornecedores e colaboradores uma ferramenta segura para se expressar perante os administradores das empresas/entidades.</p>

<h4><strong>Auditoria de Diagnóstico</strong></h4>

<p style="text-align: justify;">Analise das principais atividades exercidas pelos funcionários e das práticas estabelecidas pelos controles internos. As revisões previstas nessa fase abrangem as várias etapas do processo produtivo e administrativo da empresa e verificam o fluxo de informações registradas nos softwares de gestão, relatórios gerenciais e demonstrações contábeis da empresa.</p> 

<p style="text-align: justify;">A auditoria de diagnóstico analisa os seguintes aspectos:</p>
<ul>
<li class="check">Gestão das disponibilidades e das contas a receber;</li>
<li class="check">Gestão dos ativos;</li>
<li class="check">Gestão dos passivos;</li>
<li class="check">Gestão do custo dos produtos vendidos;</li>
<li class="check">Gestão contábil</li>
<li class="check">Gestão recursos humanos</li>
<li class="check">Gestão tecnologia de informação</li>
</ul>
<p style="text-align: justify;">Os resultados apurados pela auditoria de diagnóstico são tabulados com base em uma matriz de riscos que estabelece os graus de risco alto, médio e baixo.</p> 
<p style="text-align: justify;">As situações que apresentarem maiores preocupações serão elencadas em um plano de ação que estabelecerá as revisões prioritárias.</p> 

<h4><strong>Auditoria de Adequação das Medidas de Ética e Conduta do Programa Empresa PróÉtica do CGU</strong></h4>

<p style="text-align: justify;">Analise e adequação das principais medidas obrigatórias e recomendadas para obtenção do cadastro do programa de Empresa PróÉtica do CGU.</p>

<p style="text-align: justify;">As revisões previstas nessa auditoria abrangem as seguintes medidas: </p>

<h5>Medidas de Ética e Conduta</h5>
<ul>
<li class="check">Regularidade com as Fazendas;</li>
<li class="check">Regularidade com FGTS;</li>
<li class="check">Não haver em seu corpo diretivo pessoas condenadas por corrupção;</li>
<li class="check">Tornar público seu compromisso com a ética e integridade e o não compactuamento com a corrupção;</li>
<li class="check">Participação da alta direção da empresa em relação a ética;</li>
<li class="check">Possuir Código de Ética que contemple: valores e princípios éticos, regras de relacionamento com o setor público, proibição de fraude e corrupção e penalidades para o caso de descumprimento das normas éticas;</li>
<li class="check">Dar ampla divulgação do Código de Conduta para os funcionários, fornecedores, clientes e parceiros;</li>
<li class="check">Possuir Comitê de Ética ou setor responsável por apurar eventuais denúncias e que tenha autonomia para atuar, protegido contra punições arbitrárias decorrentes de suas atribuições;</li> 
<li class="check">Disponibilizar canais de contato para orientação e esclarecimento de dúvidas de seus funcionários sobre questões legais e éticas.</li>
</ul>
<h5>Controle Interno</h5>
<ul>
<li class="check">Possuir sistema de informação contábil que identifique origem de receitas e controle de despesas;</li>
<li class="check">Possuir auditoria interna e submeter-se a auditoria externa independente;</li>
<li class="check">Disponibilizar canais de denúncia aos seus funcionários, colaboradores e público externo, resguardando o anonimato e oferecendo proteção contra despedida de funcionários que denunciarem de boa-fé;</li>
<li class="check">Possuir Politica de Prevenção e Gerenciamento de Riscos de Fraude e/ou Corrupção, que preveja em seus contratos: proibição de fraude e corrupção, penalidades para aqueles que descumprirem normas éticas;</li>
<li class="check">Rotatividade entre funcionários que atuam em áreas vulneráveis; </li>
<li class="check">Regra sobre doações filantrópicas e patrocínios;</li>
</ul>

<h5>Relacionamento com o Setor Público</h5>
<ul>
<li class="check">Possuir regras sobre encaminhamento de eventuais atos de corrupção e improbidade à autoridade pública, conduta dos funcionários com o Poder Público e medidas para conscientizar e orientar os funcionários sobre essas normas;</li>
<li class="check">Possuir política e normas de: prevenção de conflitos de interesse entre o público e privado, contratação de ex-servidores públicos para evitar conflito de interesses, oferecimento de presentes, brindes e outros benefícios a funcionários públicos e proibição de reuniões entre um funcionário da empresa e o Poder Público;</li>
<li class="check">Orientar os funcionários a denunciarem atos de corrupção de que tenham conhecimento;</li>
<li class="check">Possuir postura clara em relação ao financiamento político, declarar os valores doados a Justiça Eleitoral, possuir política de não apoiar candidato com histórico de corrupção e acompanhar a correta declaração do candidato à Justiça Eleitoral;</li> 
<li class="check">Consultar o Cadastro da CGU de empresas inidôneas e suspensas ao efetuar contratações;</li>
</ul>

<h5>Capacitação e Treinamento</h5>
<ul>
<li class="check">Oferecer capacitação em ética aos funcionários e colaboradores, englobando conduta ética nos negócios, na participação em licitações e contratos, na prevenção de conflito de interesses, no relacionamento com agentes públicos, suborno transnacional, gestão de riscos e de fraudes e corrupção.</li>
<li class="check">Incentivar participação dos funcionários, possuir material didático sobre ética, integridade e combate a corrupção;</li>
<li class="check">Oferecer capacitação especifica para os ocupantes de cargos diretivos e treinamento para os novos funcionários e colaboradores;</li>
</ul>
<h5>Transparência</h5>
<ul>
<li class="check">Disponibilizar identificação e função de seus principais executivos no sitio eletrônico da empresa;</li>
<li class="check">Publicar seus balanços financeiros e informações sobre contratos firmados com a Administração Pública;</li>
<li class="check">Tornar públicas suas doações filantrópicas e divulgar em seu sitio doações feitas a candidatos e partidos políticos;</li>
<li class="check">Realizar e divulgar relatório de sustentabilidade.</li>
</ul>

<h5>Ações Coletivas</h5>
<ul>
<li class="check">Ser signatária do Pacto pela Integridade e contra a Corrupção;</li>
<li class="check">Estar associada ao Pacto Global da ONU, Iniciativa de Parceria contra a Corrupção do Fórum Econômico Mundial.</li>
<li class="check">Fazer parte de outras ações coletivas voltadas a prevenção e ao combate à corrupção, por meio, por exemplo, de associação com outras empresas/entidades.</li>
</ul>
<h4><strong>Auditoria Inteligência Mensal</strong></h4>

<p style="text-align: justify;">Diferentemente da auditoria tradicional, a auditoria de integência tem foco na apresentação de soluções às inconsistências idetificadas nos resultados. Dessa maneira, as correções necessárias podem ser implementadas imediatamente, com a concordância dos executivos envolvidos.</p>
<p style="text-align: justify;">Há ainda que se destacar que a auditoria de inteligencia desenvolvida por nossos consultores se dá em situações de anormalidade apontadas no mapa de diagnóstico, de forma a permitir a identificação da ocorrência de fraudes ou desvio de conduta de funcionários e colaboradores.</p>
<p style="text-align: justify;">Realiza mensalmente (prazo previsto em contrato) trabalhos de auditoria com base matriz de riscos elaborada na fase de aduditoria de diagnóstico e nas demandas apresentados pelos executivos da diretoria.</p>

<p style="text-align: justify;">O escopo das auditorias de inteligências abrangem as seguintes atividades:</p>

<h5>Financeiro</h5>
<ul>
<li class="check">Contagem física de caixa;</li>
<li class="check">Análise das conciliações dos saldos bancários;</li>
<li class="check">Apuração das transações registradas na contabilidade em dinheiro;</li>
<li class="check">Identificação dos valores mantidos em aplicações financeiras;</li>
<li class="check">Controle dos recebíveis baixados da contabilidade por inadimplência;</li>
<li class="check">Análise das conciliações dos saldos de clientes;</li>
<li class="check">Identificação e controle de outros créditos;</li>
<li class="check">Avaliação da gestão de valores adiantados a terceiros e funcionários;</li>
<li class="check">Inspeção documental das transações efetuadas através do bank line e com uso de código de barras.</li>
</ul>
<h5>Estoques</h5>
<ul>
<li class="check">Realização ou análise do resultado de inventários físicos;</li>
<li class="check">Analise de aquisições de insumos em trânsito;</li>
<li class="check">Checagem dos critérios na gestão de peças e materiais de reposição;</li>
<li class="check">Identificação de estoques obsoletos;</li>
<li class="check">Checagem dos controles de estoques enviados para beneficiamento;</li>
<li class="check">Análise dos procedimentos de baixa de estoques por perdas.</li>
</ul>
<h5>Investimentos em bens e participações societárias</h5>
<ul>
<li class="check">Análise documental das aquisições de bens e de documentos societários;</li>
<li class="check">Verificação de posições de passivos nas controladas e coligadas que possam afetar os negócios da investidora;</li>
<li class="check">Checagem dos rendimentos obtidos e a gestão de amortizações de ágios/deságios.</li>
</ul>
<h5>Ativo Imobilizado</h5>
<ul>
<li class="check">Verificação dos controles e da gestão dos bens tangíveis e intangíveis;</li>
<li class="check">Realização ou análise do resultado de inventários físicos;</li>
<li class="check">Checagem dos relatórios com a relação dos bens individualizados;</li>
<li class="check">Avaliação da gestão de veículos locados/arrendados;</li>
<li class="check">Inspeção das ordens de serviços de reparos e melhorias na vida útil de máquinas e equipamentos;</li>
<li class="check">Análise da apuração do custo ativável de obras em andamento e projetos de ampliações do parque industrial;</li>
<li class="check">Checagem por amostragens de recuperabilidade do custo de ativos (Impairment Test).</li>
</ul>
<h5>Passivos Financeiros</h5>
<ul>
<li class="check">Análise do Aging-List dos fornecedores de produtos e serviços;</li>
<li class="check">Checagem do comportamento dos saldos de credores diversos;</li>
<li class="check">Realização por amostragem de inspeção física dos documentos suporte das contas a pagar;</li>
<li class="check">Revisão dos empréstimos bancários e identificação dos bens dados em garantia;</li>
<li class="check">Análise de contratos de mútuos com empresas coligadas e controladas;</li>
<li class="check">Realização de conciliação da posição do saldo devedor de financiamentos e eventuais cláusulas de assunções de aditivos contratuais por inadimplência;</li>
<li class="check">Conciliação dos valores em aberto dos tributos, impostos e contribuições sociais com a posição da conta corrente da Receita Federal e das demais Secretarias Estaduais e Municipais;</li>
<li class="check">Avaliação dos critérios de constituição de provisões de contingências e de ajustes contábeis.</li>
</ul>
<h5>Recursos Humanos</h5>
<ul>
<li class="check">Verificação dos controles de apontamentos de horas;</li>
<li class="check">Análise dos procedimentos de cálculos de proventos e descontos em folha;</li>
<li class="check">Checagem dos prontuários dos funcionários;</li>
<li class="check">Verificação do cálculo de férias e rescisões;</li>
<li class="check">Avaliação da gestão da CIPA;</li>
<li class="check">Análise do perfil de reclamações trabalhistas.</li>
</ul>
<h5>Tecnologia da Informação</h5>
<ul>
<li class="check">Verificação dos procedimentos de segurança da informação;</li>
<li class="check">Análise dos procedimentos internos de uso de e-mail e acessos na internet;</li>
<li class="check">Avaliação de procedimentos de back-up e recuperação de dados;</li>
<li class="check">Consistência de rastreabilidade de acesso ao sistema;</li>
<li class="check">Integridade de dados compartilhados com sistemas independentes;</li>
<li class="check">Controle de equipamentos externos (lap tops).</li>
</ul>
<h5>Patrimônio Liquido</h5>
<ul>
<li class="check">Análise da evolução da constituição de reservas de lucros;</li>
<li class="check">Revisão dos critérios contábeis de apuração dos dividendos e cálculo de juros sobre o capital próprio.</li>
</ul>
<h5>Resultado do Exercício</h5>
<ul>
<li class="check">Conciliação das receitas de vendas contabilizadas com as notas fiscais registradas nos livros fiscais;</li>
<li class="check">Verificação da razoabilidade das vendas canceladas, abatimentos e das deduções de vendas;</li>
<li class="check">Avaliação dos relatórios gerenciais de apurações dos custos de produtos vendidos;</li>
<li class="check">Identificação de despesas administrativas e operacionais estranhas e anormais em relação ao perfil do negócio da empresa, e em especial aos seguintes tópicos:</li>
</ul>
<ul>
<li class="star">Serviços prestados;</li>
<li class="star">Contribuições e doações;</li>
<li class="star">Despesas com veículos e viagens;</li>
<li class="star">Perdão de dívida;</li>
<li class="star">Cartões de créditos;</li>
<li class="star">Despesas em nome de terceiros</li>
</ul>


<h5>Apurações de Procedimentos Tributários</h5>

<p style="text-align: justify;">Nosso projeto estabelece ainda serviços de auditoria tributária, com revisões periódicas dos procedimentos fiscais de apuração dos tributos de natureza federal, estadual e municipal, sobre o faturamento, na folha de pagamento e verbas rescisórias e no cálculo do imposto de renda e contribuição do social nos resultados das empresas.</p>
<p style="text-align: justify;">Apresentação de diagnóstico das tarefas desenvolvidas pelos responsáveis do departamento fiscal e da contabilidade das empresas nos seguintes aspectos:</p>
<ul>
<li class="check">Cumprimento das disposições tributárias vigentes; </li>
<li class="check">Existência de controles internos e prestações de informações perante as exigências das obrigações acessórias;</li>
<li class="check">Identificação de cálculos incorretos ou interpretações legais inadequadas;</li>
<li class="check">Oportunidade de planejamento tributário para redução da carga tributária;</li>
<li class="check">Recuperação de créditos tributários no âmbito federal e estadual através da realização de conciliações das bases de cálculo dos tributos com a escrituração contábil e fiscal.</li>
</ul>
<h5>Apurações de Fraudes</h5>

<p style="text-align: justify;">No que se refere aos trabalhos de auditoria de inteligência e gerenciamento de riscos, a PróÉtica desenvolverá caso seja necessário, as seguintes atividades:</p>
<ul>
<li class="check">Estudo de todos os fatos irregulares apurados durante a realização dos trabalhos de auditoria com o objetivo de identificar o modus operandi, os principais suspeitos e o montante da perda;</li>
<li class="check">Levantar o background-check dos suspeitos, visando identificar fatos que permitam evidenciar o desvio de conduta profissional e pessoal no sentido de corroborar os apontamentos das irregularidades;</li>
<li class="check">Elaboração de relatório de forma clara e conclusiva dos fatos apurados, viabilizando ao cliente a tomada de possíveis ações cíveis e criminais das pessoas envolvidas na fraude.</li>
</ul>

<h4><strong>Programa de Variações Patrimoniais</strong></h4>

<p style="text-align: justify;">Desenvolveremos mensalmente acompanhamento das informações mantidas nas demonstrações contábeis, vez que muitas vezes inconsistências são identificadas analisando o perfil das contas patrimoniais e de resultado, pois é comum desvio de recursos serem escondidos em contas não auditadas.</p>  
<p style="text-align: justify;">Nossa metodologia é tabelar todas as contas do ativo, passivo, despesas e receitas a cada final de mês e comparar a evolução dos saldos, caso haja situações que fogem dos padrões normais da empresa, essas situações serão objeto de auditoria contábil de inteligência.</p>

<h4><strong>Help Desk Emergencial</strong></h4>

<p style="text-align: justify;">Nosso projeto disponibilizará aos nossos clientes um Help Desk na área de tecnologia de informação para dar suporte emergencial aos funcionários chaves da empresa. Faremos mensalmente rotinas de auditoria de inteligência em contratos com fornecedores e prestadores de serviços</p>

<h4><strong>Revisões de Contratos</strong></h4>

<p style="text-align: justify;">As revisões abrangem análises de contratos com fornecedores e prestadores de serviços dos clientes, para identificar situações de riscos como clausulas leoninas, multas indevidas de rescisões e inadimplência, vigências de prazos indefinidos e falta de proteções legais e aditivos indevidos.</p> 
 
</div>
</div>

<span class="acc-trigger"><a href="#"><strong>4. Metodologia:</strong></a></span>
<div class="acc-container">
<div class="content">
<p style="text-align: justify;">Os trabalhos de consultoria serão desenvolvidos com base nos documentos disponibilizados pelo cliente, informações verbais e escritas prestadas por funcionários da empresa e, ainda, em dados obtidos perante órgãos púbicos municipais, estaduais e federais.</p> 
<p style="text-align: justify;">A metodologia contemplará a análise crítica dos relatórios gerenciais, financeiros e contábeis apresentados e dos documentos das pastas dos funcionários disponibilizados pelo cliente.</p>
<p style="text-align: justify;">Pesquisas em bancos de dados, juntas comerciais, mídias, tribunais e em qualquer outro órgão público que se faça necessário.</p>


</div>
</div>

<span class="acc-trigger"><a href="#"><strong>5. Relatórios e Material de Referência:</strong></a></span>
<div class="acc-container">
<div class="content">
<p style="text-align: justify;">Ao término dos trabalhos mensais, a Pró-Ética elaborará um relatório final contendo todas as informações apuradas, com recomendações e conclusões sobre o que foi apresentado. O relatório apresentará, dentre outros itens, a metodologia de trabalho empregada, as informações relevantes coletadas e analisadas durante o processo, incluindo cópias de documentos pertinentes, e as medidas corretivas propostas.</p>
</div>
</div>


<span class="acc-trigger"><a href="#"><strong>6. Prazo:</strong></a></span>
<div class="acc-container">
<div class="content">
<p style="text-align: justify;">Estima-se que para esse projeto será necessário um prazo mínimo de 6 meses, a contar da aprovação desta proposta. </p>
</div>
</div>

<span class="acc-trigger"><a href="#"><strong>7. Honorários e Despesas:</strong></a></span>
<div class="acc-container">
<div class="content">
<p style="text-align: justify;"><a href="/contato"> Entre em contato para obter informações </a></p>
</div>
</div>

<span class="acc-trigger"><a href="#"><strong>8. Impostos:</strong></a></span>
<div class="acc-container">
<div class="content">
<p style="text-align: justify;"><a href="/contato"> Entre em contato para obter informações </a></p>
</div>
</div>




</div>

<div class="vertical-space1"></div>
<div class="contact-form">
<div class="clr"></div><br />
<h4>Entre em contato:</h4>
<form action="" method="post" id="frmContact">
<h5>Qual o seu nome?</h5>
<input name="txtName" type="text" class="txbx" value="" placeholder="Seu Nome"/><br />
<h5>Qual o seu email?</h5>
<input name="txtEmail" type="text" class="txbx" value="" placeholder="Seu Email" /><br />
<h5>Assunto</h5>
<input name="txtSubject" type="text" class="txbx" value="" placeholder="Assunto" /><br />
<div class="erabox">
<h5>Sua Mensagem</h5>
<textarea name="txtText"cols="" rows="" class="txbx era" ></textarea><br />
<input name="" type="button" class="sendbtn" value="Enviar Mensagem" id="btnSend"/>

<div id="spanMessage">
</div>
</div>
</form>
</div><!-- end-contact-form  -->

</section>


<script>
$().ready(function(){

var $container = $('.acc-container'),
	$trigger   = $('.acc-trigger');

$container.hide();
$trigger.first().addClass('active').next().show();

var fullWidth = $container.outerWidth(true);
$trigger.css('width', fullWidth);
$container.css('width', fullWidth);

$trigger.on('click', function(e) {
	if( $(this).next().is(':hidden') ) {
		$trigger.removeClass('active').next().slideUp(300);
		$(this).toggleClass('active').next().slideDown(300);
	}
	e.preventDefault();
});

// Resize
$(window).on('resize', function() {
	fullWidth = $container.outerWidth(true)
	$trigger.css('width', $trigger.parent().width() );
	$container.css('width', $container.parent().width() );
});

});



</script>