<section id="headline2">
<div class="container">
<h3>Código de Ética<small>Este é um modelo do código de ética.</small></h3>
</div>
</section>

<section class="container" >
<div class="vertical-space1"></div>
<div class="sixteen columns">
<div class="title">
<h4>Comportamento Ético e Conduta</h4>
</div>
<p style="text-align: justify;">O comportamento ético e a conduta íntegra são o caminho para o sucesso nos negócios. A conquista por parte das empresas da boa reputação no desenvolvimento de suas atividades e no reconhecimento da confiabilidade pública são pilares da gestão moderna e na certificação da qualidade dos serviços prestados e dos bens produzidos.</p>
<p style="text-align: justify;">Os princípios e valores éticos devem abranger a globalidade dos relacionamentos mantidos pelas empresas, exigindo das pessoas que a representam uma forma responsável de gerir os negócios. </p>
<p style="text-align: justify;">Cientes da importância do deselvolvimento de um Código de Ética por parte das empresas, disponibilizamos aqui alguns itens básicos que devem integrar esse documento. O modelo que apresentamos, não descarta a necessidade de discussão e maior aprofundamento das questões éticas pelos funcionários, colaboradores e administradores, trabalho no qual a Pró-Ética pode ajudá-lo.</p>
<p style="text-align: justify;">A Pró-Ética desenvolve, em conjunto com a empresa, um Código de Conduta personalizado, de acordo com as especificidades da sua empresa.</p> 


<h4><strong>O Código de Conduta Ética Corporativo:</strong></h4>
<p style="text-align: justify;">O comportamento ético é um dos alicerces das empresas, sendo assim, a elaboração de um guia contendo informações e ações de postura ética é um importante instrumento na conscientização dos funcionários e agentes de relacionamento interno e externo.</p>
<p style="text-align: justify;">O código de conduta ética é uma coletânea das principais atitudes que devem ser tomadas nas mais diversas situações que envolvem as rotinas de trabalho e atividades compartilhadas com colaboradores, fornecedores, parceiros, clientes, sociedade, comunidade e governo.</p>
<p style="text-align: justify;">Um código de ética e conduta tem como parte fundamental o compromisso dos funcionários com os valores e princípios básicos da empresa.</p>


<h4><strong>Princípios Básicos</strong></h4>

<p style="text-align: justify;"><strong>Integridade</strong> - Conduta honesta, harmonia e equilíbrio pessoal nas relações profissionais e de negócios;</p>
<p style="text-align: justify;"><strong>Liberdade</strong> – Autonomia para agir e fundamentar suas atitudes e ações conforme a sua própria consciência. Poder para decidir sobre o seu destino, consciente de suas limitações e da responsabilidade pelos seus atos;</p>
<p style="text-align: justify;"><strong>Lealdade</strong> – Relacionamento sincero, franco e honesto, fidelidade aos compromissos, sem perder a imparcialidade necessária e a consciência do que é correto e justo;</p>
<p style="text-align: justify;"><strong>Justiça</strong> – Defesa da integridade, da liberdade e da lealdade próprias e das demais pessoas. Dar tratamento igual, imparcial e isento de interesses particulares, favorecendo um ambiente de trabalho saudável e espontâneo, que proporcione crescimento pessoal.</p>

<h4><strong>Aplicação do Código de Ética e Conduta Corporativa</strong></h4>

<p style="text-align: justify;">O Código será aplicado pelas empresas e abrangerá os seguintes agentes nos seus relacionamentos internos e externos:</p>
<p style="text-align: justify;"><strong>Empregados e colaboradores: </strong>Todas as pessoas que participam nas atividades das empresas, podendo ser: administradores, empregados, prestadores de serviços e consultores;</p>
<p style="text-align: justify;"><strong>Fornecedores: </strong>Todos os participantes da cadeia de suprimentos das empresas que compõe os processos de negócios, tais como fornecedores de materiais, de equipamentos e de serviços;</p>
<p style="text-align: justify;"><strong>Clientes: </strong>Pessoas físicas ou jurídicas que adquirem os produtos ou a prestação de serviços da empresa;</p>
<p style="text-align: justify;"><strong>Sociedades e comunidades atendidas: </strong>são organizações, instituições e entidades da sociedade civil representativas da cidadania, dos clientes, de segmentos empresariais, órgãos de comunicação, institutos de pesquisa, organizações de promoção e desenvolvimento social;</p>
<p style="text-align: justify;"><strong>Governo: </strong>Instâncias dos Poderes Executivo, Legislativo e Judiciário, nos níveis Federal, Estadual e Municipal, órgão reguladores, comissões parlamentares, órgãos de defesa do consumidor e de proteção ao meio ambiente.</p>
<p style="text-align: justify;">Deve ser garantida a ampla divulgação do Código de Ética e Conduta Corporativa a todos os agentes supracitados.</p>


<h4><strong>Orientações sobre comportamento no ambiente de Trabalho</strong></h4>

<h4><strong>Cumprimento da Legislação e Regulamentos</strong></h4>

<p style="text-align: justify;">Todos os funcionários e representantes da empresa devem cumprir a legislação nacional e os regulamentos que estejam relacionados com suas atividades e devem se assegurar de que, sob nenhuma hipótese, sua conduta possa ser interpretada como descumprimento às leis aplicáveis e aos regulamentos que orientam as atividades da empresa.</p>


<h4><strong>Informação Confidencial</strong></h4>

<p style="text-align: justify;">Informações confidenciais são patrimônio da empresa. A nenhum funcionário é permitido revelar esse tipo de informação fora da empresa, sob qualquer circunstância.</p>
<p style="text-align: justify;">Informações confidenciais são aquelas que ainda não sejam de domínio publico, ou que a empresa não tencione ou deseje divulgar ou ainda as que possam de alguma maneira comprometer o posicionamento de mercado da empresa.</p>
<p style="text-align: justify;">Alguns exemplos de informações confidenciais são:</p>
<ul>
	<li class="check">Informações técnicas sobre processos atuais ou futuros;</li>
	<li class="check">Planejamento de compras, listas de fornecedores e preços;</li>
	<li class="check">Custo de produção, valor de venda do produto ou ações estratégicas;</li>
	<li class="check">Dados referentes às aquisições, fusões e novos projetos, dentre outras.</li>
</ul>	
<p style="text-align: justify;">Todos os funcionários devem ter atenção com os locais onde discutem assuntos da empresa. Não é apropriado discutir assuntos confidenciais na presença de pessoas não autorizadas, nem mesmo com familiares e amigos que, inadvertidamente, podem repassar essas informações para outras pessoas.</p>
<p style="text-align: justify;">Por questões de negócios, informações confidenciais podem ser mencionadas para terceiros, desde que à Área Jurídica da empresa seja contatada com antecedência para preparação de acordo que inclua as necessárias salvaguardas. Os seguintes cuidados devem ser observados:</p>
<ul>
	<li class="check">Ninguém deve passar ou utilizar informações confidenciais da empresa para obter ganhos pessoais de qualquer natureza;</li>
	<li class="check">Obter informações confidenciais de terceiros sem o devido respaldo legal é impróprio, antiético e pode colocar a empresa em situação de risco legal;</li>
	<li class="check">Nenhuma pessoa deve ser empregada na empresa com o intuito exclusivo de obter informações confidenciais de outra empresa.</li>
</ul>


<h4><strong>Conflito de Interesses</strong></h4>

<p style="text-align: justify;">O conflito de interesses é contraposição entre o interesse da empresa e o interesse pessoal de quem a representa, ele ocorre quando o empregado utiliza sua influência ou comete atos com o intuito de beneficiar interesses particulares que se contrapõem aos interesses da empresa ou podem causar danos ou prejuízo patrimonial.</p> 
<p style="text-align: justify;">O empregado não poderá realizar atividades externas, como prestar consultoria ou ocupar cargo em organizações com interesses conflitantes ou que realizem negócios com a empresa.</p>
<p style="text-align: justify;">Vínculos societários próprios ou por intermédio de familiares com fornecedores ou concorrentes da empresa não são aceitos, se o cargo que o empregado ocupa lhe conferir o poder de influenciar transações ou permitir acesso a informações privilegiadas.</p>
<p style="text-align: justify;">O empregado que ocupar posições em entidades externas deve comunicar à sua chefia imediata, por escrito, que avaliará possíveis conflitos de interesse e a concorrência com o horário de trabalho.</p>


<h4><strong>Informações privilegiadas</strong></h4>

<p style="text-align: justify;">O empregado que, por força de seu cargo ou de suas responsabilidades, tenha acesso a informações sobre a empresa, que ainda não tenham sido divulgadas publicamente, não pode transacionar títulos ou ações dessas empresas ou passá-las a terceiros durante o período de confidencialidade.</p>
<p style="text-align: justify;">Em atenção ás regras de sigilo, os aspectos morais e éticos devem ser observados, de forma que os funcionários não se utilizem de informações privilegiadas para benefício próprio, evitando a negociação de ações de sua propriedade, bem como a divulgação de quaisquer informações relevantes à negociação de ações da empresa durante os seguintes períodos:</p>
<ul>
	<li class="check">2 (dois) meses que antecedem a publicação dos resultados financeiros anuais;</li>
	<li class="check">2 (dois) meses que antecedem as publicações de seus resultados financeiros semestrais e;</li>
	<li class="check">Durante qualquer período em que ocorram fatos relevantes que direta ou indiretamente possam constituir variações da valorização das ações dos funcionários e cuja respectiva cotação ainda não tenha sido publicada.</li>
</ul>	


<h4><strong>Preconceito</strong></h4>

<p style="text-align: justify;">Não é admitido discriminação ou preconceito de qualquer natureza, seja por raça, religião, faixa etária, sexo, convicção política, nacionalidade, estado civil, orientação sexual ou condição física.</p>


<h4><strong>Igualdade de Oportunidades</strong></h4>

<p style="text-align: justify;">É assegurada igualdade de oportunidade para recrutamento de novos funcionários, garantindo que a demonstração de interesse de um empregado em participar de um processo de recrutamento interno seja visto pela sua chefia como uma alternativa normal de evolução de carreira, não podendo ser ensejo a nenhuma retaliação.</p>
<p style="text-align: justify;">O recrutamento interno dará prioridade para funcionários e em seguida para a comunidade local. O processo de recrutamento e seleção será aberto por meio de publicações internas e externas, de forma absolutamente transparente, respeitando os seguintes princípios:</p>
<ul>
	<li class="check">A admissão de funcionários com grau de parentesco e ex-funcionários deve respeitar o critério de que familiares, nos casos de pais, filhos, irmãos e cônjuges não podem exercer funções no mesmo departamento, mesmo que um destes seja funcionário de empresa contratada;</li>
	<li class="check">A contratação de ex-funcionários não deve ocorrer nos casos em que o empregado tenha se desligado em função de desvio de conduta, improbidade administrativa ou outra forma que tenha justificado o desligamento</li>
</ul>	


<h4><strong>Uso dos sistemas eletrônicos de informações</strong></h4>

<p style="text-align: justify;">A empresa permite a utilização moderada dos sistemas eletrônicos para fins pessoais, desde que esse uso não prejudique o andamento do trabalho e não contrarie os seguintes critérios:</p>
<ul>
	<li class="check">A veiculação de informações deve estar relacionada obrigatoriamente à atividade profissional e não pode conter mensagens obscenas, correntes de arrecadação de recursos, ofensivas, profanas ou preconceituosas, ficando o empregado ciente de que em algumas circunstâncias poderá haver a necessidade de que seja examinado o conteúdo das mensagens;</li>
	<li class="check">O uso de senhas é pessoal e intransferível a terceiros;</li>
	<li class="check">Não podem ser copiados softwares protegidos por direitos autorais ou desenvolvidos internamente e/ou por contratos de licenciamento ou que não são apropriados para uso em serviço;</li>
</ul>	


<h4><strong>Drogas e Álcool</strong></h4>

<p style="text-align: justify;">É proibido o consumo de bebidas alcoólicas no horário de trabalho e a entrada na empresa em estado de embriaguez. É igualmente proibido o uso ou porte de drogas e a permanência no ambiente de trabalho em estado alterado pelo uso dessas substâncias.</p>


<h4><strong>Assédio sexual</strong></h4>

<p style="text-align: justify;">Não é admitido assédio sexual. </p>
<p style="text-align: justify;">O assédio sexual é caracterizado pelo uso de posição privilegiada na hierarquia da empresa para obter favor ou vantagem sexual.</p>


<h4><strong>Violência no Local de Trabalho</strong></h4>

<p style="text-align: justify;">Comportamentos violentos de qualquer natureza, desde ameaças verbais ou físicas, intimidação, roubo ou qualquer conduta similar não serão admitidos no ambiente corporativo e devem ser imediatamente comunicado aos seus superiores imediatos.</p> 


<h4><strong>Abuso de Poder</strong></h4>

<p style="text-align: justify;">Todo ocupante de cargo de chefia, em cada área, deve exercer sua autoridade com respeito aos princípios de não discriminação e tratamento justo. Todos os funcionários têm o direito de contestar e apelar a instâncias superiores em relação a decisões tomadas pelas chefias imediatas que os afetem diretamente.</p>


<h4><strong>Atividades Políticas e Afiliações Partidárias</strong></h4>

<p style="text-align: justify;">Os funcionários são livres para participar do processo político-eleitoral. Porém, tal participação deve ocorrer em seu tempo livre e à sua própria causa. Recursos, espaço e imagem da empresa não podem ser usados para atender a interesses políticos pessoais ou partidários.</p>


<h4><strong>Brindes e Presentes</strong></h4>

<p style="text-align: justify;">A oferta, pagamento, solicitação ou aceitação de subornos, sob qualquer forma, representa prática inaceitável e será considerado descumprimento do Código de Conduta. </p>
<p style="text-align: justify;">Não é permitido aos funcionários aceitar presentes ou vantagens em nome da empresa, em seu próprio nome ou no de sua família, que caracterizem comprometimento de sua situação profissional e dos objetivos da empresa. As diretrizes básicas de comportamento sobre o assunto são:</p>
<ul>
	<li class="check">Nenhum funcionário está autorizado a fornecer qualquer coisa de valor incluindo alimentos ou bebidas (limitados a refeições durante visitas), gorjetas, transporte, acomodação em hotéis, passagens aéreas ou terrestres para qualquer funcionário público sem a prévia autorização da gerência da empresa;</li>
	<li class="check">Comunicação imediata de qualquer recebimento de proposta de suborno vinda de funcionário público ao seu superior imediato;</li>
	<li class="check">Não aceitar presentes de fornecedores cujo valor exceda ao eticamente razoável, tais como brindes institucionais (camisetas, chaveiros, canetas, agendas). Qualquer presente recebido por um funcionário que exceda os limites razoáveis deve ser imediatamente comunicado ao seu superior imediato;</li>
	<li class="check">Funcionários cuja rotina de trabalho inclua contatos externos poderão oferecer refeições (jantares e almoços), desde que esses encontros tenham caráter claro de negócios;</li>
	<li class="check">Convites para eventos com despesas custeadas por clientes, fornecedores, órgãos governamentais e outros, somente podem ser aceitos quando existir a real oportunidade de desenvolvimento do contato comercial, que tenham sido estendidos também a profissionais de outras empresas e mediante aprovação da gerência.</li>
</ul>

<h4><strong>Fraudes e Roubos</strong></h4>

<p style="text-align: justify;">Situações envolvendo fraudes ou roubos serão rigorosa e prontamente investigadas pela empresa, relatadas e, quando apropriado, os envolvidos remetidos aos órgãos punitivos competentes.</p>
<p style="text-align: justify;">Situações de roubo e fraudes abrangem uma avaliação do contexto das irregularidades e abrangem também os seguintes preceitos:</p>
<ul>
	<li class="check">Negligência intencional ou emprego errado dos procedimentos e normas da empresa que permitiu a ocorrência das irregularidades;</li>
	<li class="check">Qualquer ganho obtido através do mau uso de autoridade outorgada pela empresa pelos funcionários envolvidos nas situações investigadas;</li>
	<li class="check">Apoio ou envolvimento de terceiros em atos de contravenção previstos na legislação vigente;</li>
	<li class="check">Retenção de qualquer informação relacionada a fraude em relação a fornecedores, clientes e agentes externos.</li>
</ul>

</div>

<div class="vertical-space1"></div>
<div class="callout">
<a class="callurl" href="/contato">Abrir</a>
<h3>Contate-nos</h3>
<p>Entre em contato e saiba como a PróÉtica pode ajudar a sua empresa com o Código de Ética</p>
</div>
</section>