<section id="headline2">
<div class="container">
<h3>FCPA<small>Foreing Corrupt Practices Act</small></h3>
</div>
</section>

<section class="container" >
<div class="vertical-space1"></div>
<div class="sixteen columns">
<h4>A FCPA (Foreing Corrupt Practices Act) foi aprovada pelo Congresso dos Estados Unidos em 1977, quando a administração publica e a preocupação com corrupção atingiu o ponto de ebulição  após o caso Watergate. Desde o ano 2000 o uso da FCPA tem se tornado cada vez mais efetiva.</h4>
<p style="text-align: justify;">A Lei torna ilegal o pagamento de qualquer tipo de suborno ou propina para agentes governamentais ou partidos políticos estrangeiros (leia-se não dos EUA) em troca de vantagens comerciais ou econômicas. Essa proibição se aplica não só  a pagamentos corruptos feitos para se obter ou reter negócios, mas qualquer tipo de suborno ou propina paga a agentes governamentais de outros países em troca de vantagens indevidas</p>
<h4>A quem se aplica?</h4>
<p style="text-align: justify;">A lei é  aplicada a empresas americanas, empresas estrangeiras e afiliadas que possuem ações negociadas nas Bolsas de Valores Americanas. Estas empresas podem ser responsabilizadas por condutas que violem as diosposições da FCPA por subornos feitos por agentes comerciais, representantes ou por terceiros em seu nome, tanto nos Estados Unidos como fora do país.Por ser abrangente e ultrapassar o terrotório das empresas e até mesmo de sua administração é que a FCPA é extremamente complexa. Sua aplicação é um processo que envolve uma série de medidas que devem ser tomados em conjunto com acionistas, sócios, administradores, funcionários, prestadores de serviços e demais representantes.</p>

<h4>A Lei:</h4>



</div>

<div class="eight columns">
<p style="text-align: justify;">Uma pessoa pode ser acusada de violar a legislação FCPA não só se tiver ciência do que está acontecendo, mas também se acreditar firmemente que uma determinada circunstância existe ou que um determinado resultado é  bastante provável. Para violar a legislação FCPA basta saber que existe uma probabilidade de que dinheiro ou outros benefícios indevidos serão usados para subornar um agente de governo estrangeiro e ignorar tal probabilidade.</p>
<p style="text-align: justify;">Uma pessoa ou empresa pode violar a ligislação FCPA sem saber com certeza que foi pago ou oferecido qualquer suborno. Esse conceito tem sido definido de formas diferentes, tais como conscientemente ignorar, cegueira propositada ou ignorar deliberadamente. Não importa a redação, simplesmente não é seguro uma pessoa manter a cabeça  enfiada na areia se souber de qualquer ciscunstância suspeita.</p>
<p style="text-align: justify;">Se ocorrer uma violação, a Companhia e o(s) indiví­duo(s) envolvido poderão estar sujeitos a penalidades monetárias substanciais. Um empregado que tenha se envolvido numa atividade ilegal também poderá estar sujeito a detenção. Por último, o empregado estará sujeito a medidas disciplinares, incluindo a demissão</p>
</div> 
<div class="eight columns">
<blockquote class="well">
<p style="text-align: justify;"><strong>Não é necessário ter ciência do pagamento de propina ou suborno para ser caracterizada como violação ao FCPA.</strong></p>
</blockquote> 
<blockquote class="well">
<p style="text-align: justify;"><strong>Código Civil Brasileiro:</strong><br> Todo administrador de sociedade, quer seja sócio ou não, passa a ser responsável pelos atos que praticar, podendo ser responsabilizado pessoalmente por todos os atos que causem danos à sociedade. (Art. 1.016)
Art. 944  O administrador será responsabilizado pelo valor integral do prejuízo que houver causado à sociedade ou a terceiros.</p>
</blockquote> 
</div>
<div class="vertical-space2"></div>
<div class="sixteen columns">
<h4><strong>Responsabilidade dos sócios/administradores</strong></h4>
</div>
<div class="vertical-space"></div>
<div class="eight columns">
<p style="text-align: justify;">Perante a FCPA: multa no valor máximo de US$ 2 milhões para companhia e instauração de processos na esfera criminal e civil aos executivos;</p>
<p style="text-align: justify;">O Departamento de Justiça dos Estados Unidos (DOJ) recomenda que, para evitar qualquer violação da Legislação FCPA, as empresas exercitem a due diligence e tomem todas as precauções possí­veis para se assegurar que seus parceiros e representantes sejam empresas ou pessoas idôneas e qualificadas.</p>
<p style="text-align: justify;">Também sugere que o processo de due diligence inclua a investigação de potenciais representantes ou parceiros de joint venture estrangeiros para determinar se de fato possuem as qualificações necessárias, se têm qualquer ví­nculo pessoal ou profissional com o governo, o número e reputação de seus clientes e sua reputação junto à Embaixada ou Consulados dos Estados Unidos e junto a bancos, clientes e outros associados locais.</p>
</div>
<div class="eight columns">
<blockquote class="well">
<p style="text-align: justify;">Mantendo a reputação:</p>
<ul>
	<li class="check"><strong>Identificar:</strong> Realizar um processo de due diligence para identificar ameaças à reputação da empresa de natureza interna e externa</li>
	<li class="check"><strong>Avaliar: </strong>Desenvolver estratégia para mitigar ou eliminar os riscos.</li>
	<li class="check"><strong>Preparar: </strong>Manter um plano de contingência que antecipe e atue sobre itens relacionados à reputação.</li>
	</ul>
	</blockquote>
</div>
<div class="vertical-space2"></div>
<div class="sixteen columns">


<h4><strong>Seleção de Parceiros Comerciais:</strong></h4>
<p style="text-align: justify;">Uma maneira de evitar problemas é tomar as medidas cabí­veis para se assegurar da competência e idoneidade do parceiro comercial (fornecedor, vendedor, cliente, terceirizado). Esse processo, se feito e documentado corretamente, irá reduzir a probabilidade de se contratar um representante de vendas que irá violar a Legislação FCPA.</p>
<h4><strong>Acordos e Contratos:</strong></h4>
<p style="text-align: justify;">Um acordo por escrito é uma maneira de impedir desentendimentos com os parceiros. Tal acordo pode ser usado para definir a relação entre a empresa e seu representante e explicitar os tipos de condutas autorizadas (aceitas) e não autorizadas (não aceitas) pela empresa. Isso ajuda a evitar problema e incentiva o representante de vendas a agir corretamente e também ajuda a empresa a eliminar representantes que se opõem a algumas condições, evitando assim problemas em potencial.</p>
<h4><strong>Alertas:</strong></h4>
<p style="text-align: justify;">Algumas situações são muito genéricas e nãoo significam que ocorreu, nem que irá ocorrer uma violação da FCPA, mas nas situações descritas abaixo é  necessário tomar cuidados especiais:</p>

	<ul>
	<li class="check">A empresa está vendendo seus produtos ou serviços em um paí­s onde sabidamente a prática de corrupção é disseminada;</li>
	<li class="check">O setor de atividades tem um histórico de corrupção;</li>
	<li class="check">A empresa foi recentemente auditada em função de pagamentos inapropriados.</li>
	</ul>

<h3><strong>Todos os funcionários e representantes da companhia, assim como suas subsidiárias, parceiros e prestadores de serviços, devem estar familiarizados com as normas da FCPA.</strong></h3>


</div>
<div class="vertical-space1"></div>
<div class="callout">
<a class="callurl" href="/contato">Abrir</a>
<h3>Contate-nos</h3>
<p>A PróÉtica pode ajudar a sua empresa a entender e aplicar o FCPA, consulte-nos </p>
</div>
</section>