 
<section id="hero" class="tbg1">

<div id="layerslider-container-fw">

<div id="layerslider" style="width: 100%; height: 249px; margin: 0px auto; ">


<div class="ls-layer" style="slidedirection: right; slidedelay: 5000; durationin: 1500; durationout: 1500;">

<img src="/images/top1.jpg" class="ls-bg" alt="">
<h5 class="ls-s-1" style="position: absolute;  top: 200px;  font-weight: normal; border-radius: 100px 100px 100px 100px; padding: 7.34375px 18.3594px;  font-size: 18.0312px; color: rgb(34, 65, 119); background: none repeat scroll 0% 0% rgb(128, 193, 229); white-space: nowrap; width: auto; height: auto; line-height: 33.0469px; border-width: 0px; opacity: 1; transform: rotate(0deg) scale(1, 1); margin-left: 0px; margin-top: 75px; display: block; visibility: visible;"> ProÉtica Ambiental, saiba como nossa proposta pode ajudar a sua empresa no caminho sustentável  <a href="/servicos/ambiental" class="green">Saiba mais</a> </h5>

</div>
<div class="ls-layer" style="slidedirection: right; slidedelay: 5000; durationin: 1500; durationout: 1500;">

<img src="/images/top2.jpg" class="ls-bg" alt="">
<h5 class="ls-s-1" style="position: absolute;  top: 200px;  font-weight: normal; border-radius: 100px 100px 100px 100px; padding: 7.34375px 18.3594px;  font-size: 18.0312px; color: rgb(34, 65, 119); background: none repeat scroll 0% 0% rgb(128, 193, 229); white-space: nowrap; width: auto; height: auto; line-height: 33.0469px; border-width: 0px; opacity: 1; transform: rotate(0deg) scale(1, 1); margin-left: 0px; margin-top: 75px; display: block; visibility: visible;"> O Projeto PróÉtica elabora um plano de auditoria fundamentado no Programa Empresa PróÉtica do CGU  <a href="/servicos/proetica" class="green">Saiba mais</a>  </h5>
</div>
<div class="ls-layer" style="slidedirection: right; slidedelay: 5000; durationin: 1500; durationout: 1500;">
<img src="/images/top3.jpg" class="ls-bg" alt="">
<h5 class="ls-s-1" style="position: absolute;  top: 200px;  font-weight: normal; border-radius: 100px 100px 100px 100px; padding: 7.34375px 18.3594px;  font-size: 18.0312px; color: rgb(34, 65, 119); background: none repeat scroll 0% 0% rgb(128, 193, 229); white-space: nowrap; width: auto; height: auto; line-height: 33.0469px; border-width: 0px; opacity: 1; transform: rotate(0deg) scale(1, 1); margin-left: 0px; margin-top: 75px; display: block; visibility: visible;">Conheça o PAI (Programa de Auditoria de Inteligência) e saiba como nós podemos ajudar a sua empresa <a href="/servicos/pai" class="green">Saiba mais</a>  </h5>

</div>
<div class="ls-layer" style="slidedirection: right; slidedelay: 5000; durationin: 1500; durationout: 1500;">

<img src="/images/top4.jpg" class="ls-bg" alt="">
<h5 class="ls-s-1" style="position: absolute;  top: 200px;  font-weight: normal; border-radius: 100px 100px 100px 100px; padding: 7.34375px 18.3594px;  font-size: 18.0312px; color: rgb(34, 65, 119); background: none repeat scroll 0% 0% rgb(128, 193, 229); white-space: nowrap; width: auto; height: auto; line-height: 33.0469px; border-width: 0px; opacity: 1; transform: rotate(0deg) scale(1, 1); margin-left: 0px; margin-top: 75px; display: block; visibility: visible;">Faça parte da rede ética e ajude-nos a dissiminar o conhecimento e a gestão ética nas empresas <a href="/cadastros/rede-etica" class="green">Saiba mais</a>  </h5>
</div>


</div>

</div>
</section>
<!-- end-hero-->
<section class="container home-content" >

<!-- Quentin-Iconbox-start -->
    <div class="vertical-space1"></div>
    <ul id="main-ibox" class="sixteen columns omega">
      <li>
        <div class="mbx-img"> <img src="/images/s-c-ico2.png" alt=""></div>
        <h5><strong>Projeto PróÉtica</strong></h5>
        <p style="text-align: justify;">O Projeto PróÉtica está fundamentado na gestão dos valores éticos corporativos através de implantação/avaliação da conscientização dos funcionários e colaboradores do Código de Conduta Ética das empresas e entidades. </p>
        <a href="/servicos/proetica" class="magicmore">Saiba mais</a></li>
      <li>
        <div class="mbx-img"> <img src="/images/s-c-ico3.png" alt=""></div>
        <h5>"PAI" <br><small> Programa de Auditoria de Inteligência</small></h5>
        <p style="text-align: justify;">O “PAI” Programa de Auditoria de Inteligência tem como metodologia a implantação mensal de uma agenda de programas de entrevistas e revisões do fluxo de informações que abrangem todas as atividades e rotinas dos diversos departamentos das empresas e entidades </p>
        <a href="/servicos/pai" class="magicmore">Saiba mais</a></li>
      <li>
        <div class="mbx-img"> <img src="/images/arvore.png" alt=""></div>
        <h5>PróÉtica Ambiental</h5>
        <p style="text-align: justify;">A PróÉtica Ambiental tem o objetivo de estabelecer a conscientização pelos empresários, empreendedores, funcionários e colaboradores na utilização dos recursos naturais, isto é estabelecer padrões similares ao Código de Conduta Ética em relação ao comportamento das atividades corporativas sobre o meio ambiente. </p>
        <a href="/servicos/ambiental" class="magicmore">Saiba mais</a></li>
        
    </ul>
    <script type="text/javascript">
		$('ul#main-ibox li:nth-child(2)').addClass('active9');
		$('ul#main-ibox li').mouseover(function() {
		$('li.active9').removeClass('active9'), $('li:hover').addClass('active9');
		}).mouseout(function() {
		$('li.active9').removeClass('active9'), $('ul#main-ibox li:nth-child(2)').addClass('active9')
		});
		</script>
    <div class="vertical-space1"></div>
	


<div class="callout">
<a class="callurl" href="/comunicacao/padrao">Abrir</a>
<h3>Canal de Comunicação</h3>
<p>O canal de comunicações  tem como objetivo informar aos gestores do projeto situações de desvio de conduta de funcionários e colaboradores e também sugestões de melhorias</p>
</div>

<div class="vertical-space1"></div>

<!-- Quentin-Iconbox-end -->

<div class="four columns alpha icon-box2 aligncenter">
<div class="columns">
<h5><strong>Código de Ética</strong></h5><br>
<img src="/images/maquina.png" alt="" height="48" width="54"><br><br>
<p style="text-align: justify;">Saiba como a ProÉtica pode ajudar a sua empresa, e acesse um modelo de código.
</p>
<a href="/documentos/codigo-etica" class="magicmore">Saiba mais</a>
</div>
</div>
<div class="four columns icon-box2 aligncenter">
<div class="columns">
<h5><strong>Rede Ética</strong></h5><br>
<img src="/images/comunidade.png" alt="" height="48" width="54"><br><br>
<p style="text-align: justify;">Cadastre-se e tenha acesso a conteúdos exclusivos, tire dúvidas e receba novidades e notícias sobre a PróÉtica.
</p>
<a href="/default/index/cadastro" class="magicmore">Saiba mais</a>
</div>
</div>


<div class="four columns icon-box2 aligncenter">
<div class="columns">
<h5><strong>FCPA</strong></h5><br>
<img src="/images/target.png" alt="" height="48" width="54" ><br><br>
<p style="text-align: justify;">A FCPA foi aprovada pelo Congresso dos Americano em 1977, quando a preocupação com corrupção atingiu ...
</p>
<a href="/documentos/fcpa" class="magicmore">Saiba mais</a>
</div>
</div>

<div class="four columns icon-box2 aligncenter">
<div class="columns">
<h5><strong>Perguntas e Respostas</strong></h5><br>
<img src="/images/faq.png" alt="" height="48" width="54"><br><br>
<p style="text-align: justify;">Acesse nossa área de perguntas e respostas e tire suas dúvidas.
</p>
<a href="/documentos/faq" class="magicmore">Saiba mais</a>
</div>
</div>
<div class="vertical-space1"></div>
<div class="four columns icon-box2 aligncenter">
<div class="columns">
<h5><strong>Quiz PróÉtica</strong></h5><br>
<img src="/images/reputation.png" alt="" height="48" width="54"><br><br>
<p style="text-align: justify;">Acesse nosso quiz e veja se sua empresa está apta a pleitear o Cadastro de Empresa PróÉtica do CGU
</p>
<a href="/pesquisas/" class="magicmore">Saiba mais</a>
</div>
</div>
<div class="vertical-space1"></div>

<?php if($this->showclientes == true){ ?>
<div class="sixteen columns">
<h4 class="subtitle">Nossos Clientes</h4>
<div class="jcarousel-container">
<div class="jcarousel-clip">
<ul id="our-clients" class="our-clients">
<li><img src="/images/clients/logomuana.png" alt=""></li>
<li><img src="/images/clients/img-logo-cemar.png" alt=""></li>
<li><img src="/images/clients/canabrava.jpg" alt=""></li>
<li><img src="/images/clients/fabinject.jpg" alt=""></li>
<li><img src="/images/clients/Logo_SC_Itajai.jpg" alt=""></li>
<li><img src="/images/clients/logo_aleia.png" alt=""></li>
<li><img src="/images/clients/asm.jpg" alt=""></li>
</ul>
</div></div>
</div>
<?php } ?>

<div class="vertical-space2"></div>
</section><!-- end- -->

<script type="text/javascript">
jQuery(document).ready(function() {

jQuery('#our-clients').jcarousel();

$('#layerslider').layerSlider({
	skinsPath : '/layerslider/skins/',
	skin : 'noskin',
	thumbnailNavigation : 'hover',
	hoverPrevNext : true,
	responsive : true,
	responsiveUnder : 900,
	thumbnailNavigation : false,
	sublayerContainer : 1000
	});
});
</script>  

