<div class="row-fluid">
<div class="span12">
<h3 class="heading"><?php echo $this->nomequiz ?> <small>Perquntas</small>
<span class="pull-right"><i style="cursor:pointer" class="splashy-document_a4_new newdepto ttip_b" title="Nova Pergunta"></i></span></h3>
<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="85%">Pesgunta</th>
<th width="10%">Opções</th>
</tr>
</thead>
<tbody>
<?php foreach($this->perquntas as $dado){ ?>
<tr>
<td width="5%"><?php echo $dado->id_registro ?></td>
<td width="85%"><?php echo $dado->pergunta ?></td>
<td width="10%"><i class="splashy-hcards_edit editdepto"  idreg="<?php echo  $dado->id_registro ?>" style="cursor:pointer" ></i> <i class="splashy-hcards_remove removedepto" idreg="<?php echo $dado->id_registro ?>" style="cursor:pointer" ></i></span></td>
</tr>
<?php }; ?>
</tbody>
</table>
</div>
</div>

<div class="modal hide fade" id="NewDepto">
   <div class="modal-header">
                        <button class="close" data-dismiss="modal">×</button>
                        <h3>Nova Pergunta:</h3>
                    </div>
<form id="newreply" name="newreply" enctype="id_note" class="form-horizontal" method="post" action="/pages/quiz/salva-pergunta">
<input type="hidden" name="id_registro" value="0" id="id_registro">
<input type="hidden" name="id_quiz" value="<?php echo $this->id_quiz?>" id="id_quiz">
<div class="modal-body">
		
		<div class="row-fluid formSep">
		<div class="span12">
		<?php echo $this->form->pergunta ?>
		</div>
		</div>
		
		<div class="row-fluid formSep">
		<div class="span6">
		<?php echo $this->form->msg_correto ?>
		</div>				
		<div class="span6">
		<?php echo $this->form->msg_errado ?>
		</div>
		
		</div>
		
		<div class="row-fluid formSep">
		<table id="tableaddchecklist"  class="table table-striped table-bordered table-condensed">
		<thead>
		<tr>
			<th width="75%">Resposta:</th>
			<th width="20%">Correta?</th>
			<th width="5%"><i class="splashy-add ttip_b addetapachecklist" title="Adicionar Etapa"></i></th>
		</tr>
		</thead>
		<tbody>
		<tr>
		<td><input type="text" name="resposta[]" id="assuntoticketeditnote" class="span12 required" value="Sim" ></td>
		<td><select name="correta[]" id="assuntoticketeditnote" class="span12 required" ><option value="1">Sim</option><option value="0">Não</option></select></td>
		<td><i class="splashy-remove_minus_sign removetrchecklist"></i></td>
		<tr>
		<td><input type="text" name="resposta[]" id="assuntoticketeditnote" class="span12 required" value="Não" ></td>
		<td><select name="correta[]" id="assuntoticketeditnote" class="span12 required" ><option value="1">Sim</option><option value="0" selected="selected">Não</option></select></td>
		<td><i class="splashy-remove_minus_sign removetrchecklist"></i></td>
		</tr>
		</tbody>
		</table>
		
		</div>

<div class="modal-footer">
<div style="text-align:right">
<a href="javascript:void(0)" class="btn btn-large btn-warning" data-dismiss="modal">Cancelar</a>
<input type="submit" name="submit" id="submiteditnote" value="Salvar" class="btn btn-large btn-primary">
</div>		
</form>
</div>
</div>

<script>
$().ready(function(){

	 $('.addetapachecklist').live('click',function () {
	        $('#tableaddchecklist > tbody:last').append('<tr><td><input type="text" name="resposta[]" id="assuntoticketeditnote" class="span12" ></td><td><select name="correta[]" id="assuntoticketeditnote" class="span12 required" ><option value="1">Sim</option><option value="0">Não</option></select></td><td><i class="splashy-remove_minus_sign removetrchecklist"></i></td></tr>');
	    });

	 $('.removetrchecklist').live('click',function () {
		 $(this).parents("tr").remove();
	    });

	$('#listaclientes').dataTable({
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		},
		"sPaginationType": "bootstrap"
                     	
                    
    });

    $(".newdepto").click(function(){
	    $("#NewDepto").modal('show');        
		
    });

    $(".editdepto").click(function(){
        id = $(this).attr('idreg');

   	 $.ajax({ 
			type: "GET", 
			url: "/pages/quiz/getquestion/id/"+ id , 
			data: "undo="+ id,
			beforeSend: function() {
								
	 		}, 
			success: function(txt) {
			
				var retorno = jQuery.parseJSON(txt);	
				$("#id_registro").val(retorno.id_registro);
				$("#id_quiz").val("<?php echo $this->id_quiz ?>");
				$("#pergunta").val(retorno.pergunta);
				$("#msg_correta").val(retorno.msg_correta);
				$("#msg_errado").val(retorno.msg_errado);
				 $("#tableaddchecklist > tbody").empty() 
				 $.each( retorno.respostas, function ( key, value ) { 
					    if(value.correct == 1){
					        $('#tableaddchecklist > tbody:last').append('<tr><td><input type="text" name="resposta[]" id="assuntoticketeditnote" class="span12" value="'+value.resposta+'" ></td><td><select name="correta[]" id="assuntoticketeditnote" class="span12 required" ><option value="1" selected="selected">Sim</option><option value="0">Não</option></select></td><td><i class="splashy-remove_minus_sign removetrchecklist"></i></td></tr>');
					    }else{
					    	$('#tableaddchecklist > tbody:last').append('<tr><td><input type="text" name="resposta[]" id="assuntoticketeditnote" class="span12" value="'+value.resposta+'" ></td><td><select name="correta[]" id="assuntoticketeditnote" class="span12 required" ><option value="1">Sim</option><option value="0" selected="selected">Não</option></select></td><td><i class="splashy-remove_minus_sign removetrchecklist"></i></td></tr>');
					    }  
	                    
	                }); 


			    $("#NewDepto").modal('show');  	

														
			}, 
			error: function(txt) { 
				$.sticky("UM ERRO DE SISTEMA OCORREU.", { type: 'st-error' });
			} 
		}); 

    });

    $(".removedepto").click(function(){
  	  	id = $(this).attr('idreg');
  	  	if(confirm("Deseja Realmente excluir este parser?")){
    	 document.location.href="/pages/quiz/removequestion/id/"+id;
  	  	}
  	  

    });

    


});


</script>
