
<section id="headline2">
<div class="container">
<h3>Nossa Equipe</h3>
</div>
</section>
<section class="container" >
<p style="text-align: justify;">A PróÉtica é uma consultoria altamente qualificada com uma equipe de profissionais com mais de 10 anos de experiência na gestão da mitigação de riscos corporativos</p>
<p style="text-align: justify;">Conheça nossos principais profissionais que possuem vasta experiência em consultoria e estão disponíveis para ajudá-lo a encontrar as melhores soluções para sua empresa.</p>

<div class="eight columns">
<!-- Testimonial -->	
<div class="testimonial-brand">
<h6><strong>CARLOS MUNERATTI</strong> <em>Idealizador</em></h6>
</div>
<div class="testimonial">
<div class="testimonial-content"><p style="text-align: justify;">Foi responsável pela Divisão de Serviços Financeiros da Kroll no Brasil, com mais de dez anos de experiência em investigação de fraudes e em elaboração de laudos contábeis judiciais e extra-judiciais. Conduziu importantes projetos nos mais diversos segmentos, como Construção Civil, Aeronáutica, Indústria Química e Setor de Serviços. Atuou como consultor no Corporate Finance e na área tributária da KPMG e como auditor Interno do Grupo Votorantim. Experiência em diversos trabalhos de investigação de fraudes como gerente da Área de Forensic da Deloitte/SP. Gerenciou, ainda, a investigação da Encol Engenharia, maior caso de falência da história do Brasil.</p>
<div class="testimonial-arrow"></div>
</div>

</div>
</div>

<div class="eight columns">
<!-- Testimonial -->	
<div class="testimonial-brand">
<h6><strong>CELSO GONÇALVES</strong></h6>
</div>
<div class="testimonial">
<div class="testimonial-content"><p style="text-align: justify;">Advogado, diretor jurídico da PróÉtica, especialista em Processo Civil, cursando especialização em Direito Empresarial. Vasta experiência em escritórios de advocacia, nas àreas de Direito Civil, Administrativo, Trabalhista, Contratual e Societário. Atuou como Gerente Jurídico de Empresas de Grande Porte com atuação nos ramos da Construção Civil, Empreendimentos Imobiliários e Transporte. Experiência em auditoria jurídica e investigativa, com projetos desenvolvidos em empresas de médio e grande porte, de diferentes setores econômicos.</p>
<div class="testimonial-arrow"></div>
</div>

</div>
</div>
<div class="vertical-space1"></div>
<div class="eight columns">
<!-- Testimonial -->	
<div class="testimonial-brand">
<h6><strong>DANIEL CHAVES</strong></h6>
</div>
<div class="testimonial">
<div class="testimonial-content"><p style="text-align: justify;">Analista de Sistemas, especializado em segurança da informação, com diversos cursos na área de tecnologia e analise forense de dados, vasta experiência em analise de Bancos de Dados e em desenvolvimento de sistemas coorporativos, evangelizador do software livre e da segurança em sistemas e redes, colaborador de diversos projetos GNU como o Linux, o PHP e outros,  </p>
<div class="testimonial-arrow"></div>
</div>

</div>
</div>

<div class="eight columns">
<!-- Testimonial -->	
<div class="testimonial-brand">
<h6><strong>LUIZ CAFARELLA</strong></h6>
</div>
<div class="testimonial">
<div class="testimonial-content"><p style="text-align: justify;">Formado em Ciências Contábeis pela Universidade Mackenzie (SP) e com diversos cursos de especialização, possui mais de 23 anos de experiência profissional adquiridos nas áreas de consultoria e auditoria da KPMG. Como Sócio-Diretor da área de Forensic Services/Risk Consulting, liderou diversos trabalhos relacionados à Prevenção e Investigação de Fraudes, Compliance, Gestão de Riscos, Auditoria Interna e Prevenção a Lavagem de Dinheiro (PLD), dentre outros, nos mais diversos ramos de atividades. Como Ouvidor devidamente certificado, foi o responsável pelo desenvolvimento do produto "Linha Ética" (Canal de Denúncia) da KPMG. Ministrou palestras ao mercado sobre os temas "Fraudes Corporativas", "PLD" e "Foreign Corrupt Practices Act (FCPA)".</p>
<div class="testimonial-arrow"></div>
</div>

</div>
</div>
</section>
