<section id="headline2">
<div class="container">
<h3>ProÉtica Ambiental</small></h3>
</div>
</section>

<section class="container" >
<div class="vertical-space1"></div>
<div class="sixteen columns">
<p style="text-align: justify;">A PróÉtica Ambiental tem o objetivo de conscientizar empresários, empreendedores, funcionários e colaboradores sobre a utilização dos recursos naturais, isto é, de estabelecer padrões similares ao Código de Conduta Ética em relação ao comportamento desses agentes nas atividades corporativas e seus efeitos sobre o meio ambiente.</p>
<p style="text-align: justify;">Exemplos de agressões ao meio ambiente resultado de decisões empresariais são extremamente abundantes e podem ser resultado de ações diretas ou indiretas, como a introdução de substâncias (químicas ou genéticas) ou energia (luz, calor, radiação) no ambiente, prejudicando o equilibrio natural. Poluição do ar,  decorrente da queima de  matéria prima como petróleo e carvão, contaminação de terras e cursos de agua, resultantes da  agricultura intensiva, desertificação e erosão dos solos  decorrentes do desmatamento de florestas e áreas de proteção ambiental, efeito estufa, consequência das enormes quantidades de óxido de carbono libertadas para a atmosfera e a destruição da camada de ozônio, dentre tantos outro.</p>
<p style="text-align: justify;">Ainda sob a perspectiva da ética ambiental surge uma nova preocupação: Como as empresas tratam os animais? A que tipo de crueldades são submetidos os animais nas indústrias farmacêutica, têxtil, de cosméticos, de entretenimento e de alimentos?</p> 
<p style="text-align: justify;">A PróÉtica Ambiental se compromete com a defesa dos animais, para tanto desenvolveu um programa de conscientização e incentivo a denúncia de situações de maus tratos.</p>
<p style="text-align: justify;">Nesse contexto e preocupada com tantas questões em torno da preservação do meio ambiente, a PróÉtica estabeleceu um canal de informações e comunicação para situações que possam resultar em danos a natureza. Esse canal de comunicação, chamado PróÉtica Ambiental tem como objetivo informar aos gestores do projeto situações de desvio de conduta de funcionários e colaboradores de empresas privadas e órgãos públicos e também sugestões de melhorias nas diversas atividades envolvidas pelos usuários do site PróÉtica.</p> 
<p style="text-align: justify;">Os formulários foram desenvolvidos para que o usuário apresente informações de forma clara e precisa e a PróÉtica Ambiental possa colaborar para que as providências cabíveis sejam alcançadas</p>


</div>

<div class="vertical-space1"></div>
	
<div class="callout">
<a class="callurl" href="/comunicacao/ambiental">Abrir</a>
<h3>Canal de Comunicação Ambiental</h3>
<p>PróÉtica Ambiental é um canal de comunicações que tem como objetivo informar aos gestores do projeto situações de desvio de conduta de funcionários e colaboradores de empresas privadas e órgãos públicos e também sugestões de melhorias nas diversas atividades envolvidas pelos usuários do site PróÉtica</p>
</div>

<div class="vertical-space1"></div>
</section>

