
<section id="headline2">
<div class="container">
<h3>PAI<small>Programa de Auditoria de Inteligência.</small></h3>
</div>
</section>

<section class="container" >
<div class="vertical-space1"></div>
<div class="sixteen columns">

<h3>Projeto PAI desenvolve programas de auditoria de inteligência de riscos de fraudes e desperdício:</h3>

<div class="vertical-space1"></div>
<p style="text-align: justify;">O PAI Programa de Auditoria de Inteligência tem como metodologia a implantação de uma agenda mensal de programas de entrevistas e revisões do fluxo de informações que abrangem todas as atividades e rotinas dos diversos departamentos das empresas e entidades.</p>
<p style="text-align: justify;">O Projeto está fundamentado na gestão dos valores éticos corporativos. Essa gestão se dará por meio da implantação/avaliação da conscientização dos funcionários e colaboradores sobre o Código de Conduta Ética das empresas e entidades e da realização de auditorias de diagnósticos que avaliam a eficiência dos procedimentos e controles internos no gerenciamento de risco de fraudes e desvios de conduta.</p>
<p style="text-align: justify;">O PAI realiza mensalmente uma auditoria de diagnóstico nas áreas financeira, comercial, administrativa e contábil de forma a identificar os procedimentos e controles internos que apresentam deficiências ou indícios de irregularidades. Os resultados serão tabulados com base em uma matriz de riscos que estabelece os graus de risco alto, médio e baixo.</p> 
<p style="text-align: justify;">As situações que apresentam maiores preocupações são elencadas em um plano de ação que estabelece as revisões prioritárias. A partir delas e por meio do desenvolvimento de técnicas de auditoria de inteligência serão identificadas situações de perdas financeiras, prejuízos patrimoniais e eventuais desvios de conduta na gestão dos procedimentos internos.</p>
<p style="text-align: justify;">O PAI está vinculado ao Portal PróÉtica, um canal de comunicação para denúncias de desvio de conduta ou sugestões de melhorias. Esse canal de comunicação tem a função de disponibilizar aos funcionários, clientes, fornecedores e colaboradores uma ferramenta segura para se expressar perante os administradores das empresas e entidades.</p>
<p style="text-align: justify;">O Projeto conta com um programa de auditoria de inteligência nas demonstrações contábeis que avaliará os saldos das contas patrimoniais e do resultado. Ao final de cada mês serão revisadas as mutações dos saldos, permitindo que situações de descontrole e operações inadequadas sejam identificadas imediatamente.</p>
<p style="text-align: justify;">Nossos clientes contarão com um Help Desk na área de tecnologia de informação para dar suporte emergencial aos funcionários chave da empresa e com rotinas mensais de auditoria de inteligência em contratos com fornecedores e prestadores de serviços.</p>
<p style="text-align: justify;">O PAI disponibiliza ainda aos seus clientes um termo de compromisso de taxa horária subsidiada, para os casos em que houver a necessidade de projetos de investigação ou perícias judiciais, decorrente da identificação de fraudes ou desvio de conduta de funcionários e colaboradores.</p>
<p style="text-align: justify;">Os resultados alcançados com o PAI auxiliam o gerenciamento da mitigação de fraudes e da qualificação nas atividades de controles internos, o que contribui diretamente para a melhoria na gestão dos negócios.</p>

</div>

<div class="vertical-space1"></div>
<div class="callout">
<a class="callurl" href="/propostas/pai">Abrir</a>
<h3>Projeto "PAI"</h3>
<p>Conheça a proposta de serviços do "PAI" ou <a href="/contato">entre em contato para maiores informações</a></p>
</div>
</section>