<section id="headline2">
<div class="container">
<h3>Projeto PróÉtica</h3>
</div>
</section>

<section class="container" >
<div class="vertical-space1"></div>
<div class="sixteen columns">

<h3>Projeto PróÉtica: Elabora um plano de auditoria fundamentado nas premissas do Programa Empresa PróÉtica da CGU – Controladoria Geral da União por meio da conscientização ética no ambiente corporativo. </h3>
 <div class="vertical-space1"></div>
<p style="text-align: justify;">O Projeto PróÉtica está fundamentado na gestão dos valores éticos corporativos. Essa gestão se dará por meio da implantação e avaliação da conscientização dos funcionários e colaboradores sobre o Código de Conduta Ética das empresas e entidades.</p>
<p style="text-align: justify;">O PróÉtica realiza mensalmente uma auditoria de diagnóstico nas àreas financeira, comercial, administrativa e contábil que avalia a eficiência dos procedimentos e controles internos no gerenciamento de riscos de fraude e desvios de conduta através de um programa de entrevistas. Essas revisões identificam os fluxos de informações das diversas rotinas de cada área e acompanham se os resultados alcançados atendem positivamente os requisitos das respostas do questionário do Projeto Empresa PróÉtica do CGU que avalia os procedimentos internos corporativos de integridade, ética e anticorrupção.</p>
<p style="text-align: justify;">As situações de procedimentos e controles internos que apresentam deficiências ou indícios de irregularidades serão tabuladas com base em uma matriz de riscos que estabelece os graus de risco alto, médio e baixo. As situações que reproduzirem não conformidade com o Projeto Empresa PróÉtica da CGU serão objeto de soluções imediatas através de ajustes nos processos das áreas afetadas.</p>
<p style="text-align: justify;">O Projeto conta com um programa de auditoria de inteligência nas demonstrações contábeis que avaliará os saldos das contas patrimoniais e do resultado. Ao final de cada mês serão revisadas as mutações dos saldos, permitindo que situações de descontrole e operações inadequadas sejam identificadas imediatamente.</p>
<p style="text-align: justify;">O PróÉtica esta vinculado ao Portal PróÉtica, um canal de comunicação para denúncias de desvio de conduta ou sugestões de melhorias. Esse canal de comunicação tem a função de disponibilizar aos funcionários, clientes, fornecedores e colaboradores uma ferramenta segura para se expressar perante os administradores das empresas/entidades.</p> 
<p style="text-align: justify;">Faremos mensalmente rotinas de auditoria de inteligência através de participações em entrevistas de desligamentos de funcionário.</p>
<p style="text-align: justify;">O PróÉtica disponibiliza ainda aos seus clientes um termo de compromisso de taxa horária subsidiada, para os casos em que houver a necessidade de projetos de investigação ou perícias judiciais, decorrente da identificação de fraudes ou desvio de conduta de funcionários e colaboradores.</p>

</div>
<div class="vertical-space1"></div>
<div class="callout">
<a class="callurl" href="/propostas/pro-etica">Abrir</a>
<h3>Projeto PróÉtica</h3>
<p>Conheça a proposta de serviços da PróÉtica ou <a href="/contato">entre em contato para maiores informações</a></p>
</div>

</section>