<script src="/js/gebo_dashboard.js"></script>
<div id="contentwrapper">
                <div class="main_content">
                    
					<div class="row-fluid">
						<div class="span12 tac">
							<ul class="ov_boxes">
								<li>
									<div class="p_bar_up p_canvas">2,4,9,7,12,8,16</div>
									<div class="ov_text">
										<strong>$3 458,00</strong>
										Novos Prospects
									</div>
								</li>
								<li>
									<div class="p_bar_down p_canvas">20,15,18,14,10,13,9,7</div>
									<div class="ov_text">
										<strong>$43 567,43</strong>
										Vendas Mensais
									</div>
								</li>
								<li>
									<div class="p_line_up p_canvas">3,5,9,7,12,8,16</div>
									<div class="ov_text">
										<strong>2304</strong>
										Prospects Aceitos 
									</div>
								</li>
								<li>
									<div class="p_line_down p_canvas">20,16,14,18,15,14,14,13,12,10,10,8</div>
									<div class="ov_text">
										<strong>30240</strong>
										Prospects Recusados
									</div>
								</li>
							</ul>
						</div>
					</div>
					<div class="row-fluid">
					 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Últimas Novidades <small>(32.DLL)</small></h3>
								<span class="pull-right label label-info ttip_t" title="Here is a sample info tooltip">Info</span>
							</div>
							sdfsdfsdf
							</div>
							
							 <div class="span6">
							<div class="heading clearfix">
								<h3 class="pull-left">Avisos do Sistema<small>(32.DLL)</small></h3>
								<span class="pull-right label label-important">Importante</span>
							</div>
							<?php if($this->UserInfo->recoverpass == 1){ ?>
							<div class="alert alert-block alert-error fade in">
								<h4 class="alert-heading">Usuário Bloqueado</h4>
								<p>Foi solicitada uma troca de senha através da recuperação de dados pelo seu usuário, ou seu cadastro é novo no sistema<br>
								Recomendamos que você troque a sua senha agora!</p>
								<p><a href="/dashboard/user/profile/" class="btn btn-inverse"> <i class="splashy-check"></i> Trocar Senha </a></p>								
							</div>
							<?php } 
							
							if($this->AlertSysMessage){
									foreach($this->AlertSysMessage as $message){
									echo $message;
									}
								};
								?>
							
						</div>
							</div>
<?php if(Cadastros_Model_Produtos::countProdutosAlerta() > 0){ ?>							
							<div class="row-fluid">
							 <div class="span12">
							<div class="heading clearfix">
								<h3 class="pull-left">Produtos em Aleta: <small>Quantidade menor que a mínima</small></h3>
								<span class="pull-right label label-important ttip_t" title="Quantidade menor que a minima!"><?php echo Cadastros_Model_Produtos::countProdutosAlerta() ?></span>
							</div>
							<table id="listaclientes" class="table table-striped table-bordered">
<thead>
<tr>
<th width="5%">ID</th>
<th width="5%">Cod Int</th>
<th width="10%">Categoria</th>
<th width="10%">Sub-Categoria</th>
<th width="45%">Produto</th>
<th width="15%">Referência</th>
<th width="5%">Estoque</th>
<th width="5%">Minimio</th>

</tr>
</thead>
<tbody>
<?php 
$produtosalerta = Cadastros_Model_Produtos::getProdutosAlerta();
foreach($produtosalerta as $prodale){ 
?>
<tr>
<td width="5%"><?php echo $prodale['id_produto'] ?></td>
<td width="5%"><?php echo $prodale['codigointerno'] ?></td>
<td width="10%"><?php echo $prodale['nomecategoria'] ?></td>
<td width="10%"><?php echo $prodale['nomesubcategoria'] ?></td>
<td width="45%"><?php echo $prodale['nomeproduto'] ?></td>
<td width="15%"><?php echo $prodale['referenciaproduto'] ?></td>
<td width="5%"><?php echo number_format($prodale['estoqueatual'],3,',','') ?></td>
<td width="5%"><?php echo number_format($prodale['estoqueminimo'],3,',','') ?></td>
</tr>
<?php  } ?>
</tbody>
</table>

				
							</div>
							
							</div>
							<?php } ?>
							
</div></div>	

<script>
$().ready(function(){

	$('#listaclientes').dataTable({
		"sPaginationType": "bootstrap",
		"oLanguage": {
			"sUrl": "/js/datatable_ptbr.txt"
		}
                    
    });


});


</script>