 <script src="/lib/tiny_mce/jquery.tinymce.js"></script>
<div class="row-fluid">
<div class="span12">
<h3 class="heading">Edição do Site</h3>
</div>
</div>
<form id="pages" name="pages" method="post" action="">
<div class="row-fluid formSep">
<div class="span12">
<?php echo $this->form->id_registro ?>
<?php echo $this->form->page?>
<?php echo $this->form->titulopagina ?>
</div>
</div>
<div class="row-fluid formSep">
<div class="span12">
<?php echo $this->form->smalltitle ?>
</div>
</div>
<div class="row-fluid formSep">
<div class="span12">
<?php echo $this->form->estilo ?>
</div>

<div class="row-fluid formSep">
<div class="span12">
<?php echo $this->form->conteudo ?>
</div>
</div>

</div>
<div class="row-fluid">
<fieldset id="fieldset-botoes">
<div style="text-align:right">
<input type="reset" name="limpar" id="limpar" value="Limpar" class="btn btn-large btn-warning">
<input type="submit" name="submit" id="submit" value="Continuar >>" class="btn btn-large btn-primary">
</div>
</fieldset>
</div>
</form>
<script>
$().ready(function(){

	$("#conteudo").tinymce({
        // Location of TinyMCE script
        script_url 							: '/lib/tiny_mce/tiny_mce.js',
        // General options
        theme 								: "advanced",
        plugins 							: "autoresize,style,table,advhr,advimage,advlink,emotions,inlinepopups,preview,media,contextmenu,paste,fullscreen,noneditable,xhtmlxtras,template,advlist",
        // Theme options
        theme_advanced_buttons1 			: "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 			: "forecolor,backcolor,|,cut,copy,paste,pastetext,|,bullist,numlist,link,image,media,|,code,preview,fullscreen",
        theme_advanced_buttons3 			: "",
        theme_advanced_toolbar_location 	: "top",
        theme_advanced_toolbar_align 		: "left",
        theme_advanced_statusbar_location 	: "bottom",
        theme_advanced_resizing 			: false,
        font_size_style_values 				: "8pt,10px,12pt,14pt,18pt,24pt,36pt"
        });

	
    


});


</script>

