<section id="headline2">
<div class="container">
<h3>Consulta de Protocolo</h3>
</div>
</section>

<section class="container" >

<div class="vertical-space1"></div>
<h4>Consulte aqui o andamento da sua comunicação:</h4>
<?php if(!$this->consulta){?>
<div class="contact-form">
<form action="" method="post">
<div class="five columns">
<h5>Protocolo:</h5>
<input name="protocolo" type="text" class="txbx" value="" placeholder="XXX-XXXX-XXXX"/>
</div>
<div class="five columns">
<h5>Senha:</h5>
<input name="senha" type="password" class="txbx" value="" placeholder=""/>
</div>
<div class="five columns">
<br>
<input name="submit" type="submit" class="sendbtn" value="Consultar" id=""/>
</div>
</form>
<div class="vertical-space1"></div>

</div>
<?php }else{ ?>
<?php if($this->info <> ''){?>
<div class="alert alert-error">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<strong>Protocolo Não Localizado, tente novamente: </strong>
<div class="vertical-space1"></div>
</div>
<div class="contact-form">
<form action="" method="post">
<div class="five columns">
<h5>Protocolo:</h5>
<input name="protocolo" type="text" class="txbx" value="" placeholder="XXX-XXXX-XXXX"/>
</div>
<div class="five columns">
<h5>Senha:</h5>
<input name="senha" type="password" class="txbx" value="" placeholder=""/>
</div>
<div class="five columns">
<br>
<input name="submit" type="submit" class="sendbtn" value="Consultar" id=""/>
</div>
</form>
<div class="vertical-space1"></div>

</div>

<?php }else{ ?>


<?php } ?>

<?php } ?>
<div class="vertical-space1"></div>
</section>
