<section id="headline2">
<div class="container">
<h3>ProÉtica
<small>Criar Chamado:</small></h3>
</div>
</section>
<section class="container page-content" >
<div class="vertical-space"></div>
<?php if($this->erro){ ?>
<div class="alert alert-error">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<strong>Você deve marcar a caixa "Declaro ter lido e compreendido os termos de uso da ProÉtica" antes de continuar!.</strong>
</div>
<div class="vertical-space"></div>
<?php } ?>
<div class="alert alert-error">
<button type="button" class="close" data-dismiss="alert">&times;</button>
<strong>Caso existam riscos de prejuízo patrimonial irreparável ou contra pessoas comunique imediatamente os fatos as autoridades locais, use o 190.</strong>
</div>
<div class="vertical-space"></div>
<h3><?php echo utf8_encode($this->data->titulochamado) ?><br><small><?php echo utf8_encode($this->data->descritivochamado) ?></small></h3>
<p style="text-align: justify;">O Canal de Comunicação foi concebido para atender as comunicações de desvio de conduta, estabelecendo tipos de chamado de acordo com as características apresentadas no modelo de código de conduta ética constante no site, recomendamos a leitura do modelo de código de conduta ética antes de efetuar o seu chamado, <a href="/documentos/codigo-etica">clique aqui para abrir</a></p>
<p style="text-align: justify;">O Canal possui algumas regras que estão apresentadas nos termos e condições. Os termos e condições do uso do site Pró-Ética têm o objetivo de esclarecer o propósito do site, bem como os parâmetros legais na utilização das informações reportadas.</p>
<div class="vertical-space"></div>
<h4>Termos de Uso da ProÉtica</h4> 
<h5>PRIVACIDADE DAS INFORMAÇÕES ENVIADAS</h5>

<p style="text-align: justify;">A Proética é um site de comunicação que proporciona aos seus usuários comunicar problemas e preocupações relacionados a situações de desvio de conduta de funcionários de empresas privadas e órgãos públicos. Os comunicados são efetivados através de relatos anônimos ou não e com total segurança e honestidade quanto a confidencialidade dos fatos reportados.</p>

<p style="text-align: justify;">Todos os relatos recebidos pela Proética são confidenciais e anônimos, desde que o usuário não revele sua identidade. O Usuário compreende e reconhece que a obrigação da Proética quanto à confidencialidade e ao anonimato em relação ao</p>
<p style="text-align: justify;">Usuário, somente se aplica ao recebimento de um comunicado de má conduta ética de pessoas e entidades privadas e públicas. Além disso, o Usuário compreende e reconhece que a Usuário não tomará nenhuma ação para resolver o assunto de nenhuma informação relatada através desse sistema por iniciativa própria.</p>

<p style="text-align: justify;">Nosso objetivo é colaborar na solução dos apontamentos através do aconselhamento ao usuário quanto as providências cabíveis em relação ao fato reportado.</p>

<p style="text-align: justify;">A Proética valoriza o direito do Usuário à privacidade de todas as informações relatadas e não revelará conscientemente nenhuma informação que identifique o Usuárior sem sua expressa permissão. Tenha cuidado para não relatar informações de modo que possam identificá-lo perante o transgressor</p>

<p style="text-align: justify;">Por exemplo, para proteger seu anonimato:</p>
<ul>
    <li class="check">Não coloque seu relacionamento com pessoas identificadas em seu relatório.</li>
    <li class="check">Não inclua sua localização física em relação a pessoas ou incidentes em seu relatório.</li>
</ul>
 <p style="text-align: justify;">A Proética usa apenas as informações apresentadas pelos Usuários para gerar um banco de dados dos casos apresentados de forma a gerar benefícios nos aconselhamentos apresentados aos próprios usuários. Ao apresentar a comunicação, você autoriza a empresa privada ou órgão publico objeto do relatório que está redigindo a coletar, processar, armazenar e, de outro modo, usar o relatório e as informações apresentadas conforme a organização julgar adequado.</p>

<h5>RESSALVAS</h5>

<p style="text-align: justify;">A Proética se reserva o direito de determinar como agir ou não agir, com base nas informações fornecidas à Proética, salvo exigência judicial contrária. Além disso, a Proética não precisa revelar nenhuma resposta ou providência fornecida pelas partes envolvidas no comunicado.</p>

<h5>COMUNICADO</h5>

<p style="text-align: justify;">Como Usuário do site de comunicação e ao enviar um comunicado à Proética o Usuário compreende e reconhece que a única obrigação da Proética é receber informações fornecidas pelo Usuário e manter a confidencialidade dos apontamentos, salvo se o Usuário autorize a transmissão dessas informações para as partes envolvidas</p>

<p style="text-align: justify;">O Usuário, em seu próprio nome, em nome de seus herdeiros, sucessores, familiares, agentes e pessoas designadas, concorda e, pelo presente, isenta a Proética e seus executivos, funcionários e pessoas designadas de e para toda e qualquer responsabilidade, reclamação, ação, causas de ação e danos relativos, nas repercussões negativas que venham a ocorrer em decorrência do apontamento do comunicado apresentado pelo Usuário</p>

<h5>RECONHECIMENTO</h5>

<p style="text-align: justify;">A Proética tem o objetivo de propagar os preceitos éticos e dos valores morais, por tanto os comunicados efetuados através deste site são levado a sério. Faça seu comunicado com a maior precisão e veracidade possíveis. Não inclua intencionalmente informações falsas ou enganosas em seu comunicado. O relato intencional de informações falsas ou enganosas pode resultar em responsabilidade civil ou criminal</p>
<div class="vertical-space"></div>

<div class="contact-form">
<form id="proetica" action="/comunicacao/novo" method="post">
<input type="hidden" name="idchamado" value="<?php echo $this->data->id_registro?>">
<input type="hidden" name="id_empresa" value="<?php echo System_Model_Empresas::getEmpresaPadrao()?>">
<label><input type="checkbox" name="checktermos" value="1">Declaro ter lido e compreendido os termos de uso da Pro&Eacute;tica</label>
<input name="submit" type="submit" class="sendbtn" value="Continuar" id=""/>
</form>
</div>

</section>

