
<link href="/multiform/styles/smart_wizard.css" rel="stylesheet" type="text/css">

<script type="text/javascript" src="/multiform/js/jquery.smartWizard-2.0.min.js"></script>

<script type="text/javascript">
    $(document).ready(function(){
    	// Smart Wizard     	
  		$('#wizard').smartWizard({
  	  	transitionEffect:'slideleft',onLeaveStep:leaveAStepCallback,onFinish:onFinishCallback,enableFinishButton:true,
    	  labelNext:'Próximo', // label for Next button
          labelPrevious:'Anterior', // label for Previous button
          labelFinish:'Finalizar' });

      function leaveAStepCallback(obj){
        var step_num= obj.attr('rel');
        return validateSteps(step_num);
      }
      
      function onFinishCallback(){
       if(validateAllSteps()){
        $('form').submit();
       }
      }
		});
	   
    function validateAllSteps(){
       var isStepValid = true;
       
       if(validateStep1() == false){
         isStepValid = false;
         $('#wizard').smartWizard('setError',{stepnum:1,iserror:true});         
       }else{
         $('#wizard').smartWizard('setError',{stepnum:1,iserror:false});
       }

       if(validateStep2() == false){
           isStepValid = false;
           $('#wizard').smartWizard('setError',{stepnum:2,iserror:true});         
         }else{
           $('#wizard').smartWizard('setError',{stepnum:2,iserror:false});
         }
       
       if(validateStep3() == false){
         isStepValid = false;
         $('#wizard').smartWizard('setError',{stepnum:3,iserror:true});         
       }else{
         $('#wizard').smartWizard('setError',{stepnum:3,iserror:false});
       }
       
       if(!isStepValid){
          $('#wizard').smartWizard('showMessage','Corrija as informações nos passos antes de continuar');
       }
              
       return isStepValid;
    } 	
		
		
		function validateSteps(step){
		  var isStepValid = true;
      // validate step 1
      if(step == 1){
        if(validateStep1() == false ){
          isStepValid = false; 
          $('#wizard').smartWizard('showMessage','Corrija as informações no passo: '+step+ '.');
          $('#wizard').smartWizard('setError',{stepnum:step,iserror:true});         
        }else{
          $('#wizard').smartWizard('setError',{stepnum:step,iserror:false});
        }
      }

      if(step == 2){
          if(validateStep2() == false ){
            isStepValid = false; 
            $('#wizard').smartWizard('showMessage','Corrija as informações no passo: '+step+ '.');
            $('#wizard').smartWizard('setError',{stepnum:step,iserror:true});         
          }else{
            $('#wizard').smartWizard('setError',{stepnum:step,iserror:false});
          }
        }
      
      // validate step3
      if(step == 3){
        if(validateStep3() == false ){
          isStepValid = false; 
          $('#wizard').smartWizard('showMessage','Corrija as informações no passo: '+step+ '.');
          $('#wizard').smartWizard('setError',{stepnum:step,iserror:true});         
        }else{
          $('#wizard').smartWizard('setError',{stepnum:step,iserror:false});
        }
      }
      
      return isStepValid;
    }
		
		function validateStep1(){
       var isValid = true; 
       // Validate Username
      
       if($('#anonimo-0').is(':checked')){
    	  var un = $('#nome').val();
       if(!un && un.length <= 0){
         isValid = false;
         $('#msg_nome').html('Por Favor informe o seu nome').show();
       }else{
         $('#msg_nome').html('').hide();
       }
       
       // validate password
       var pw = $('#celular').val();
       if(!pw && pw.length <= 0){
         isValid = false;
         $('#msg_celular').html('Informe um celular para contato').show();         
       }else{
         $('#msg_celular').html('').hide();
       }
       

       var email = $('#email').val();
       if(email && email.length > 0){
         if(!isValidEmailAddress(email)){
           isValid = false;
           $('#msg_email').html('Email Invalido').show();           
         }else{
          $('#msg_email').html('').hide();
         }
       }else{
         isValid = false;
         $('#msg_email').html('Informe seu email').show();
       }       
     
       }

       var pw = $('#sexo').val();
       if(!pw && pw.length <= 0){
         isValid = false;
         $('#msg_sexo').html('Informe o seu sexo!').show();         
       }else{
         $('#msg_sexo').html('').hide();
       }

       var pw = $('#faixaetaria').val();
       if(!pw && pw.length <= 0){
         isValid = false;
         $('#msg_faixaetaria').html('Informe sua faixa etaria!').show();         
       }else{
         $('#msg_faixaetaria').html('').hide();
       } 
        
       return isValid;
    }

		  function validateStep2(){
		      var isValid = true;    
		      //validate email  email
		      var email = $('#emailempresa').val();
		       if(email && email.length > 0){
		         if(!isValidEmailAddress(email)){
		           isValid = false;
		           $('#msg_emailempresa').html('Email Inválido').show();           
		         }else{
		          $('#msg_emailempresa').html('').hide();
		         }
		       }else{
		         isValid = false;
		         $('#msg_emailempresa').html('Informe um email').show();
		       }

		       var pw = $('#tiporelacao').val();
		       if(!pw && pw.length <= 0){
		         isValid = false;
		         $('#msg_tiporelacao').html('Informe sua relação com a empresa').show();         
		       }else{
		         $('#msg_tiporelacao').html('').hide();
		       }   

		       var pw = $('#temporelacao').val();
		       if(!pw && pw.length <= 0){
		         isValid = false;
		         $('#msg_temporelacao').html('Informe o tempo da relação').show();         
		       }else{
		         $('#msg_temporelacao').html('').hide();
		       }

		       var pw = $('#nomeempresa').val();
		       if(!pw && pw.length <= 0){
		         isValid = false;
		         $('#msg_nomeempresa').html('Informe o nome da empresa').show();         
		       }else{
		         $('#msg_nomeempresa').html('').hide();
		       }      

		       var pw = $('#telefoneempresa').val();
		       if(!pw && pw.length <= 0){
		         isValid = false;
		         $('#msg_telefoneempresa').html('Informe um telefone').show();         
		       }else{
		         $('#msg_telefoneempresa').html('').hide();
		       } 
		      return isValid;
		    }
    
    function validateStep3(){
      var isValid = true;    

      var pw = $('#tipoinfracao').val();
      if(!pw && pw.length <= 0){
        isValid = false;
        $('#msg_tipoinfracao').html('Informe o tipo de infração').show();         
      }else{
        $('#msg_tipoinfracao').html('').hide();
      }

      
      if($('#perdafinanceira-1').is(':checked')){
    	  var pw = $('#estimaperda').val();
          if(!pw && pw.length <= 0){
            isValid = false;
            $('#msg_estimaperda').html('Qual a estimativa de perda?').show();         
          }else{
            $('#msg_estimaperda').html('').hide();
          }    

      }

      if($('#gerencia-1').is(':checked')){
    	  var pw = $('#quemenvolvido').val();
          if(!pw && pw.length <= 0){
            isValid = false;
            $('#msg_quemenvolvido').html('Informe de quem você suspeita?').show();         
          }else{
            $('#msg_estimaperda').html('').hide();
          }    

      }

      var pw = $('#relato').val();
      if(!pw && pw.length <= 0){
        isValid = false;
        $('#msg_relato').html('Nos informe o seu relato').show();         
      }else{
        $('#msg_relato').html('').hide();
      }    

      
      
      return isValid;
    }
    
    // Email Validation
    function isValidEmailAddress(emailAddress) {
      var pattern = new RegExp(/^(("[\w-\s]+")|([\w-]+(?:\.[\w-]+)*)|("[\w-\s]+")([\w-]+(?:\.[\w-]+)*))(@((?:[\w-]+\.)*\w[\w-]{0,66})\.([a-z]{2,6}(?:\.[a-z]{2})?)$)|(@\[?((25[0-5]\.|2[0-4][0-9]\.|1[0-9]{2}\.|[0-9]{1,2}\.))((25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\.){2}(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[0-9]{1,2})\]?$)/i);
      return pattern.test(emailAddress);
    } 

    
$("#anonimo-1").click(function(){
	$("#nome").val('');
	$('#nome').attr("readonly", "readonly");

	$("#email").val('');
	$('#email').attr("readonly", "readonly");

	$("#celular").val('');
	$('#celular').attr("readonly", "readonly");

});	

$("#anonimo-0").click(function(){
	$("#nome").val('');
	$('#nome').removeAttr("readonly");

	$("#email").val('');
	$('#email').removeAttr("readonly");

	$("#celular").val('');
	$('#celular').removAattr("readonly");

});	

		
</script>
       
<section id="headline2">
<div class="container">
<h3>ProÉtica
<small>Criar Chamado:</small></h3>
</div>
</section>
<section class="container page-content" >
<div class="vertical-space"></div>
<div class="alert alert-info">
<p style="text-align: justify;"><strong><?php echo utf8_encode($this->data->titulochamado) ?>:</strong>
<?php echo utf8_encode($this->data->descritivochamado) ?>
</p>
</div>
<div class="vertical-space"></div>


<form action="/comunicacao/salvar" method="POST">
  <input type='hidden' name="id_chamado" value="<?php echo $this->data->id_registro ?>">
  <input type='hidden' name="id_empresa" value="<?php echo $this->id_empresa?>">
<!-- Tabs -->
  		<div id="wizard" class="swMain">
  			<ul>
  				<li><a href="#step-1">
                <label class="stepNumber">1</label>
                <span class="stepDesc">
                   Seus Dados
                </span>
            </a></li>
  				<li><a href="#step-2">
                <label class="stepNumber">2</label>
                <span class="stepDesc">
                   Empresa
                </span>
            </a></li>
  				<li><a href="#step-3">
                <label class="stepNumber">3</label>
                <span class="stepDesc">
                   Comunicação
                   
                </span>
             </a></li>
  				
  			</ul>
  			<div id="step-1">	
            <h2 class="StepTitle">Passo 1: Seus Dados</h2>
            <div class="vertical-space"></div>
            
            <div class="four columns">
            <h6>Deseja ficar anonimo?</h6>
            </div>
            <div class="five columns">
           <input type="radio" name="anonimo" id="anonimo-0" value="0" checked="checked" >Não   <input type="radio" name="anonimo" id="anonimo-1" value="1">Sim
            </div>
            <div class="five columns">
            <span id="msg_anonimo"></span>
            </div>
            <div class="vertical-space"></div>
                
            <div class="four columns">
            <h6>Seu Nome:</h6>
            </div>
            <div class="seven columns">
            <input name="nome" id="nome" type="text" class="txbx" value="" placeholder="Seu Nome"/>
            </div>
            <div class="five columns">
            <span id="msg_nome"></span>
            </div>
            <div class="vertical-space"></div>
            
             <div class="four columns">
            <h6>Seu Email:</h6>
            </div>
            <div class="four columns">
            <input name="email" id="email" type="text" class="txbx" value="" placeholder="Seu Email"/>
            <span id="msg_email"></span>
            </div>
            <div class="four columns">
            <h6>Celular:</h6>
            </div>
            <div class="four columns">
            <input name="celular" id="celular" type="text" class="txbx" value="" placeholder="Seu Celular"/>
            
            <span id="msg_celular"></span>
            </div>
            <div class="vertical-space"></div>
            
             <div class="four columns">
            <h6>Sexo:</h6>
            </div>
            <div class="four columns">
            <select name="sexo" id="sexo">
            <option value=""> - Selecione -</option>
            <option value="1">Masculino</option>
            <option value="2">Feminino</option>
            </select>
            
            <span id="msg_sexo"></span>
            </div>
            <div class="four columns">
            <h6>Faixa Etária:</h6>
            </div>
            <div class="four columns">
            <select name="faixaetaria" id="faixaetaria">
            <option value=""> - Selecione -</option>
            <option value="1">Até 20 Anos</option>
            <option value="2">21 a 30 Anos</option>
            <option value="3">31 a 40 Anos</option>
            <option value="4">41 a 50 Anos</option>
            <option value="5">51 a 60 Anos</option>
            <option value="6">Acima de 60Anos</option>
            
            </select>
            
            <span id="msg_faixaetaria"></span>
            </div>
            <div class="vertical-space"></div>
            
                			
        </div>
  			<div id="step-2">
            <h2 class="StepTitle">Passo 2: Dados da Empresa</h2>
              <div class="vertical-space"></div>
                <div class="four columns">
            <h6>Qual a sua relação com a empresa?</h6>
            </div>
            <div class="four columns">
            <select name="tiporelacao" id="tiporelacao">
            <option value=""> - Selecione -</option>
            <option value="1">Funcionário Efetivo</option>
            <option value="2">Temporário</option>
            <option value="3">Prestador de Serviços</option>
            <option value="4">Terceirizado</option>
            <option value="5">Outros</option>
            </select>
            
            <span id="msg_tiporelacao"></span>
            </div>
            <div class="four columns">
            <h6>Qual o tempo dessa relação?:</h6>
            </div>
            <div class="four columns">
            <select name="temporelacao" id="temporelacao">
            <option value=""> - Selecione -</option>
            <option value="1">Até 01 ano</option>
            <option value="2">de 01 a 03 anos</option>
            <option value="3">de 04 a 06 anos</option>
            <option value="4">de 07 a 10 anos</option>
            <option value="5">superior a 10 anos</option>
                  
            </select>
            
            <span id="msg_temporelacao"></span>
            </div>
            <div class="vertical-space"></div>
              <div class="four columns">
            <h6>Tipo de Empresa</h6>
            </div>
            <div class="four columns">
            <input type="radio" name="tpempresa" id="tpempresa-0" value="0"  >Pública   <input type="radio" name="tpempresa" id="tpempresa-1" value="1" checked="checked">Privada
            
            <span id="msg_tpempresa"></span>
            </div>
            <div class="four columns">
            <h6>Nome da Empresa:</h6>
            </div>
            <div class="four columns">
           <input name="nomeempresa" id="nomeempresa" type="text" class="txbx" value="" placeholder="Nome da Empresa"/>
            
            <span id="msg_nomeempresa"></span>
            </div>
            
              <div class="vertical-space"></div>
              <div class="four columns">
            <h6>Telefone</h6>
            </div>
            <div class="four columns">
            <input name="telefoneempresa" id="telefoneempresa" type="text" class="txbx" value="" placeholder="Tel Comercial"/>
            
            <span id="msg_telefoneempresa"></span>
            </div>
            <div class="four columns">
            <h6>Email:</h6>
            </div>
            <div class="four columns">
           <input name="emailempresa" id="emailempresa" type="text" class="txbx" value="" placeholder="Email da empresa"/>
            
            <span id="msg_emailempresa"></span>
            </div>
            
              <div class="vertical-space"></div>
              <div class="four columns">
            <h6>Melhor horário de contato</h6>
            </div>
            <div class="four columns">
            <select name="melhorhorario" id="melhorhorario">
            <option value=""> - Selecione -</option>
            <option value="1">Comercial Seg/Sex</option>
            <option value="2">Qualquer Horário</option>
          
            </select>
            
            <span id="msg_melhorhorario"></span>
            </div>
            <div class="four columns">
            <h6>Podemos enviar esse comunicado a empresa?:</h6>
            </div>
            <div class="four columns">
           <input type="radio" name="envioempresa" id="envioempresa-0" value="0"  >Não   <input type="radio" name="envioempresa" id="envioempresa-1" value="1" checked="checked">Sim
            
            <span id="msg_envioempresa"></span>
            </div>
            
             
            
            
              	
                
        </div>                      
  			<div id="step-3">
            <h2 class="StepTitle">Step 3: Comunicação</h2>	
              <div class="vertical-space"></div>
              <div class="four columns">
            <h6>Tipo de Infração</h6>
            </div>
            <div class="four columns">
            <select name="tipoinfracao" id="tipoinfracao">
            <option value=""> - Selecione -</option>
            <option value="1">Societária</option>
            <option value="2">Comercial</option>
            <option value="3">Trabalhista</option>
            <option value="4">Tributária</option>
            <option value="5">Criminal</option>
            <option value="6">Código de Defesa do Consumidor</option>
            <option value="7">Outros</option>
            </select>
                        <span id="msg_tipoinfracao"></span>
            </div>
            <div class="four columns">
            <h6>Houve Perda Financeira?</h6>
            </div>
            <div class="four columns">
            <input type="radio" name=perdafinanceira id="perdafinanceira-0" value="0"  >Não   <input type="radio" name="perdafinanceira" id="perdafinanceira-1" value="1" checked="checked">Sim          
            <span id="msg_perdafinanceira"></span>
            </div>
            <div class="vertical-space"></div>
                  
            
            <div class="four columns">
            <h6>De quanto você estima a perda?</h6>
            </div>
            <div class="four columns">
             <select name="estimaperda" id="estimaperda">
            <option value=""> - Selecione -</option>
            <option value="1">Até 50 Mil </option>
            <option value="2">de 51 a 100 Mil</option>
            <option value="3">de 101 a 500 Mil</option>
            <option value="4">de 500 a 1 Milhão</option>
            <option value="5">Acima de 1 Milhão</option>
            </select>
             <span id="msg_estimaperda"></span>
            </div>
              <div class="four columns">
            <h6>Você suspeita ou sabe se a gerência está envolvida?</h6>
            </div>
            <div class="four columns">
             <input type="radio" name="gerencia" id="gerencia-0" value="0"  >Não   <input type="radio" name="gerencia" id="gerencia-1" value="1" checked="checked">Sim <input type="radio" name="gerencia" id="gerencia-2" value="2" checked="checked">Prefiro não Informar
             <span id="msg_gerencia"></span>
            </div>
            <div class="vertical-space"></div>
              <div class="four columns">
            <h6>Se sim Quem?:</h6>
            </div>
            <div class="four columns">
           <input name="quemenvolvido" id="quemenvolvido" type="text" class="txbx" value="" placeholder="Nome da pessoa"/>
            <span id="msg_quemenvolvido"></span>
            </div>
                <div class="four columns">
            <h6>Deseja receber esse chamado em seu email??</h6>
            </div>
            <div class="four columns">
             <input type="radio" name="chamadoemail" id="chamadoemail-0" value="0"  >Não   <input type="radio" name="chamadoemail" id="chamadoemail-1" value="1" checked="checked">Sim 
             <span id="msg_chamadoemail"></span>
            </div>
            <div class="vertical-space"></div>
              <div class="sixteen columns">
            <h6>De o seu relato: (Como você ficou sabendo do problema?)</h6>
            </div>
             <div class="sixteen columns">
           <textarea name="relato" cols="" rows="8" class="txbx era" style="width: 100%" id="relato" ></textarea>
            </div>
             <div class="vertical-space"></div>
            
           
        </div>
  		
  		</div>
<!-- End SmartWizard Content -->  		
</form> 

<div class="vertical-space2"></div>
</section>
