
<section id="headline2">
<div class="container">
<h3>ProÉtica
<small>Criar Chamado:</small></h3>
</div>
</section>
<section class="container page-content" >
<div class="vertical-space"></div>
<div class="alert alert-info">
<p style="text-align: justify;"><strong><?php echo utf8_encode($this->data->titulochamado) ?>:</strong>
<?php echo utf8_encode($this->data->descritivochamado) ?>
</p>
</div>
<div class="vertical-space"></div>
<h3>Obrigado!</h3>
<p style="text-align: justify;"><strong>Recebemos a sua comunicação em <?php echo date('d/m/Y H:i')?> e a ela determinamos um protocolo e uma senha para seu acesso e controle futuros por favor tome nota:</strong></p>
<h4>Protocolo: <?php echo$this->form['protocolo']?></h4>
<h4>Senha: <?php echo$this->form['password']?></h4>

<?php if($this->form['chamadoemail'] == 1){ ?>
<div class="vertical-space"></div>
<p style="text-align: justify;"><strong>Em breve você receberá em seu email: <?php echo $this->form['email']?> uma cópia desta comunicação</strong></p>
<?php } ?>

<?php if($this->form['envioempresa'] == 1){ ?>
<div class="vertical-space"></div>
<p style="text-align: justify;"><strong>De acordo com sua autorização em breve entraremos em contato com a empresa para informar o seu relato, lembrando que seus dados não são divulgados a empresa.</strong></p>
<?php } ?>
<div class="vertical-space"></div>
</section>